source "https://rubygems.org"

gem "tty-reader", "~> 0.9"
gem "tty-prompt", "~> 0.23"
gem "tty-spinner", "~> 0.9"
gem "tty-table", "~> 0.12"
gem "tty-box", "~> 0.7"
gem "tty-markdown", "~> 0.7"
gem "tty-progressbar", "~> 0.18"
gem "tty-cursor", "~> 0.7"
gem "pastel", "~> 0.8"
gem "rouge", "~> 4.0"
gem "falcon", "~> 0.47"

group :test do
  gem "minitest", "~> 5.0"
  gem "minitest-reporters", "~> 1.6"
end
