- GENERATES HTML AND PDF BUSINESS PLANS FROM YML
- USES HTU LETTERS AS FOUNDATION FOR COMMON CSS LAYOUT
- ADHERES TO MASTER'S RULES AND LAWS
- PRIMARY LANGUAGE IS NORWEGIAN (WWW.SNL.NO)
- SEE HTTPS://GITHUB.COM/ANON987654321/PUB AND PUB2 AND PUB3 TO RESTORE ALL ORIGINAL IDEAS
- ROBERT BRINGHURST - THE ELEMENTS OF TYPOGRAPHIC STYLE
- STRUNK & WHITE - THE ELEMENTS OF STYLE

