#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerate scripts/improvement_titles.txt from canonical 320-item backlog.
TITLES = [
  # P0 1-10
  "Reconcile 455k vs 150k legat ceiling with explainer",
  "Innovasjon Norge sendable false until meeting booked",
  "Align clinical language (ikke diagnose) across legats",
  "Fix manifest project rails to pub_healthcare for Helse Vest",
  "Fix typo applikasjaser in consolidated letter",
  "Remove unverified 72-100 forbedringsforslag metric",
  "WCAG AAA to WCAG 2.2 AA-mal",
  "Payment amounts server-side only from funding.yml",
  "Unify send_legats.sh guards with grok_send_legats.rb",
  "Global AI-utkast disclaimer on all letters",
  # A content 11-55
  "Align Gunvor Minde track bolig across YAML batches HTML",
  "Align Zuccarelli track bolig across YAML batches HTML",
  "Soften brgen dating/takeaway/TV in funder-facing letters",
  "Drop +15pp valgdeltakelse 2028 without measurement plan",
  "Add personal.html plan brofinansiering not AI-wrapped",
  "Render fun_wholesome_table on index",
  "Per-funder vedlegg-sjekkliste in manifest",
  "Gunvor Minde required-doc table from stipendportalen 4974",
  "Utdanningsstiftelse split utdanning vs kompetanseheving angles",
  "Merge duplicate Sept deadline rows",
  "Implement maritim template in bergen_catalog.yml",
  "Dedicated Wahlstrom to Repligen legat from funders.wahlstrom",
  "Norwegian Hedge Finanstilsynet banner on all letters",
  "SYRE legat embed assets/ivaar_fkyeah images",
  "Ilumi sample fastprisliste appendix",
  "pub.attorney Advokatloven block on every civic legat",
  "Trond Mohn pre-qual checklist and UiB contact placeholder",
  "Nordic Innovation English abstract paragraph",
  "Anders Jahre institutional partner disclaimer",
  "Startlan trio 12 62 64 boligpakke shared doc list",
  "65_legathandboken_generell internal index only not outbound",
  "63_nav clarify NAV service not grant",
  "Revmatikerforbundet child/pårørende angle not generic helse",
  "Mental Helse vs Autismeforening distinct templates",
  "vx_* matrix low_priority collapse in UI",
  "Per-legat cover_intro override in YAML",
  "amount field in catalog wired to budget section",
  "Portal-only funders auto sendable false",
  "preferred_channel email portal meeting per funder",
  "One-page executive summary per venture",
  "Standardize section numbering across all letters",
  "Reduce vx_* duplication merge when 80pct identical",
  "Westfal-Larsen budget from bsdports venture",
  "Anthon tie to documented workshop curriculum",
  "Media City split brgen TV vs Repligen deliverables",
  "ExxonMobil utdanning angle not generic AI",
  "Kavli Trust measurable samfunnsnytte KPIs",
  "Consolidate Det Bergenske and ditt_parti if redundant",
  "Hielmstierne 3-year Bergen residency rule from funders",
  "Autismeforening honest fit check or soften angle",
  "Footer clarify Johann vs GK Tepstad roles",
  "Add soknadsportal URL per funder where applicable",
  "Legat index group by frist not only alphabetical",
  "fun_* drafts link to real channel in each body",
  "LLM tailoring pass with mandatory human review gate",
  # B financial 56-85
  "Explain ask_in_nok > project_total_nok in budget tables",
  "portfolio.legat_sum_explainer block on index",
  "Cashflow month-by-month per venture in funding.yml",
  "Validate developer_hourly_nok x hours vs dev line items",
  "Portfolio columns likviditet skattefradrag lan",
  "SkatteFUNN compute from FoU hours not flat 100k",
  "IN egenandel calculator typical 25pct per venture",
  "SYRE COGS per prototype pair",
  "Amber kost per plagg brukt metric",
  "Sovereign VPS CapEx vs OpEx split",
  "Sensitivity page 50 100 150pct legat success",
  "norwegian_hedge hide IN ask until Finanstilsynet dialog",
  "Bolig apartment price band vs kommune maks kjopesum",
  "Export funding.yml to CSV for regnskapsforer",
  "Kontoplan mapping per breakdown line",
  "Buffer pct rule documented per venture",
  "Machine-readable excludes anti-double-dip pairs",
  "Personal 35k ask aligned with 10-50k brofinansiering",
  "Radio Bergen bandwidth cost per episode",
  "Repligen equipment depreciation line",
  "Convergence version auto-bump on economics edit",
  "Year-1 vs Year-2 funding split for IN applications",
  "Living costs bridge 18k/mnd x months until payout",
  "Explicit what we will NOT spend on per venture",
  "Tax timing note for ENK MVA threshold",
  "SkatteFUNN eligible hours log template",
  "Egeninnsats valuation existing MASTER/RAILS codebase",
  "Break-even timeline per venture honest",
  "funding_forecast.yml multi-year 2026-2028",
  "Rails scenario planner 2 legater + delvis IN",
  # C automation 86-115
  "Initialize legats/sent_log.yml with schema comment",
  "--confirm before non-dry-run send",
  "Dry-run writes .eml to legats/outbox/",
  "Auto-build frist_host_2026 batch from funding.deadlines",
  "Strip non-sendable IDs from batches automatically",
  "Email verify script compare to vs contact_url",
  "PDF via headless Chrome when wkhtmltopdf missing",
  "Attach PDF and HTML when sending",
  "MIME hash in sent_log for dedup integrity",
  "BCC archive to applicant inbox",
  "Daily send cap and rate limit",
  "Batch run report Markdown after send",
  "Mutt cover templates per track covers/bolig.txt",
  "Exclude fun_* 66_*_draft self-to from all_sendable",
  "html_to_text parity shell vs Ruby single implementation",
  "Stipendportalen deadline scrape YAML diff manual approve",
  "Cron and reminder doc for Sept frister",
  "Slack/email notify on successful send",
  "--id single send with pre-flight checklist output",
  "Legat PDF naming convention id_funder_date.pdf",
  "Queue failed sends for retry",
  "verify_to true block send until manually cleared",
  "Cover letter tone slider formal warm minimal",
  "Attach funding.yml venture excerpt as appendix optional",
  "Log mutt exit codes and stderr in sent_log",
  "Batch delay jitter to avoid spam filters",
  "Separate from display name vs envelope",
  "Reply-To routing for funder responses",
  "Grok suggest-only mode for cover tweaks never auto-send",
  "Rails submissions table audit trail",
  # D static HTML 116-140
  "role=table script in build_legats.rb",
  "meta description per plan/legat",
  "Self-host EB Garamond in htu/fonts/",
  "Unify lang=nb static and Rails",
  "@media print in htu.css",
  "th scope=col in all generated tables",
  "rel=canonical per page",
  "data-plan data-funder-id on articles",
  "Prev/next nav in PLAN_ORDER on each plan",
  "legats/index.html filter chips by track JS",
  "sitemap.xml for content",
  "robots.txt",
  "OpenGraph for shareable plans",
  "Last built from funding.generated",
  "SYRE figures figcaption and credits",
  "Logo aria-hidden or meaningful alt",
  "Minified HTU CSS build step",
  "HTML5 validator in CI",
  "Mobile typography fixes in htu.css",
  "prefers-color-scheme dark mode screen only",
  "Internal anchor TOC on long plans",
  "Consistent amp vs and in titles",
  "Favicon and apple-touch-icon Rails and static",
  "JSON-LD Organization for PubHealthcare",
  "Pagefind static search over plans and legats",
  # E Rails 141-170
  "Legats index draft sendable badges",
  "Legats index sort by deadline",
  "Deadline calendar on /legats",
  "Filter legats by track query param",
  "Legat show manifest metadata to frist notes verify_url",
  "Plans index TRL track ask columns",
  "Plan show prev/next navigation",
  "Portfolio page from funding_helpers",
  "Deadlines page and ICS export",
  "API /api/plans JSON",
  "API /api/legats JSON",
  "Payments server-side amount from catalog",
  "CSP initializer for BPLAN rails",
  "catalog.rb mtime cache and sanitize",
  "Home bolig CTA block",
  "Track pills in site.css",
  "SitemapsController and RobotsController",
  "show_pay_buttons ENV gate",
  "not_found helper",
  "Attachment checklist on legat show",
  "Verify banner on legat show",
  "Portfolio convergence version in footer",
  "Rails tests for catalog payments deadlines",
  "bplan.sh deploy script separate from RAILS/apps.yml",
  "public/content symlink to BPLAN root",
  "Makefile bplan validate build test",
  "test/validate_test.rb Bplan::Validate",
  "test/build_plans_test.rb subprocess build",
  ".github/workflows/bplan.yml CI",
  "bplan.sh reads .deployignore",
  # F deploy ops 171-195
  "OPENBSD etc/rc.d/bplan from rails-app.tmpl",
  "relayd entry bplan.pub.healthcare to 39282",
  "Run bplan.sh on OpenBSD VPS",
  "BPLAN_VIPPS_NUMBER in /etc/bplan.env",
  "Staging domain for BPLAN",
  "Blue/green deploy for BPLAN",
  "Live Vipps webhooks",
  "NSD zone bplan.pub.healthcare",
  "acme-client cert for bplan.pub.healthcare",
  "Litestream backup for BPLAN sqlite",
  "Falcon workers tuning for BPLAN",
  "Health check /up in relayd",
  "rcctl restart relayd after bplan deploy",
  "bplan user and directory layout on VPS",
  "Sync content tree on deploy",
  "BUILD_ID stamp on VPS",
  "Deploy smoke test bplan.pub.healthcare",
  "Operator runbook section for BPLAN",
  "PATH_OWNERSHIP.yml bplan entry",
  "master.json bplan app entry",
  "deploy_all.sh includes bplan",
  "vps_install_all bplan bundle",
  "bplan.env.sample committed",
  "Doas rules for bplan deploy",
  "bplan.sh BUILD_ID check and stamp",
  # G testing CI 196-215
  "Testing and CI improvement 196",
  "Testing and CI improvement 197",
  "Testing and CI improvement 198",
  "Testing and CI improvement 199",
  "Testing and CI improvement 200",
  "Testing and CI improvement 201",
  "Testing and CI improvement 202",
  "Testing and CI improvement 203",
  "Testing and CI improvement 204",
  "Testing and CI improvement 205",
  "Testing and CI improvement 206",
  "Testing and CI improvement 207",
  "Testing and CI improvement 208",
  "Testing and CI improvement 209",
  "Testing and CI improvement 210",
  "Testing and CI improvement 211",
  "Testing and CI improvement 212",
  "Testing and CI improvement 213",
  "Testing and CI improvement 214",
  "Testing and CI improvement 215",
  # H UX 216-235
  "Color-coded track pills helse bolig innovasjon",
  "Deadline urgency highlight 7 days or less",
  "Label pay buttons brostotte vs offisiell soknad",
  "Bolig forst CTA when bolig_asap pending",
  "Focus-visible styles in site.css",
  "Reduce text-align justify on mobile",
  "Empty state for filtered legats",
  "Print-friendly payment instructions",
  "Inline SVG track icons no CDN",
  "Flash styling for payment redirect",
  "Legat show sticky send checklist sidebar",
  "Home hero clearer BPLAN vs RAILS vs MASTER hierarchy",
  "Typography scale audit EB Garamond meta size",
  "Table zebra striping optional in HTU",
  "Payment page step 1 Vipps step 2 mailto fallback",
  "Venture cards on /plans instead of plain table",
  "Progress ring X of Y Sept frister prepared",
  "Reduce visual noise on legat table pagination",
  "Portfolio dashboard charts from funding.yml",
  "Printable soknadspakke bundle per batch",
  # I legal 236-255
  "Legal and honesty improvement 236",
  "Legal and honesty improvement 237",
  "Legal and honesty improvement 238",
  "Legal and honesty improvement 239",
  "Legal and honesty improvement 240",
  "Legal and honesty improvement 241",
  "Legal and honesty improvement 242",
  "Legal and honesty improvement 243",
  "Legal and honesty improvement 244",
  "Legal and honesty improvement 245",
  "Legal and honesty improvement 246",
  "Legal and honesty improvement 247",
  "Legal and honesty improvement 248",
  "Legal and honesty improvement 249",
  "Legal and honesty improvement 250",
  "Legal and honesty improvement 251",
  "Legal and honesty improvement 252",
  "Legal and honesty improvement 253",
  "Legal and honesty improvement 254",
  "Legal and honesty improvement 255",
  # J MASTER docs 256-270
  "MASTER RAILS documentation improvement 256",
  "MASTER RAILS documentation improvement 257",
  "MASTER RAILS documentation improvement 258",
  "MASTER RAILS documentation improvement 259",
  "MASTER RAILS documentation improvement 260",
  "MASTER RAILS documentation improvement 261",
  "MASTER RAILS documentation improvement 262",
  "MASTER RAILS documentation improvement 263",
  "MASTER RAILS documentation improvement 264",
  "MASTER RAILS documentation improvement 265",
  "MASTER RAILS documentation improvement 266",
  "MASTER RAILS documentation improvement 267",
  "MASTER RAILS documentation improvement 268",
  "MASTER RAILS documentation improvement 269",
  "MASTER RAILS documentation improvement 270",
  # K convergence 271-285
  "Convergence validation improvement 271",
  "Convergence validation improvement 272",
  "Convergence validation improvement 273",
  "Convergence validation improvement 274",
  "Convergence validation improvement 275",
  "Convergence validation improvement 276",
  "Convergence validation improvement 277",
  "Convergence validation improvement 278",
  "Convergence validation improvement 279",
  "Convergence validation improvement 280",
  "Convergence validation improvement 281",
  "Convergence validation improvement 282",
  "Convergence validation improvement 283",
  "Convergence validation improvement 284",
  "Convergence validation improvement 285",
  # L new legats ops 286-300
  "New legats and funders improvement 286",
  "New legats and funders improvement 287",
  "New legats and funders improvement 288",
  "New legats and funders improvement 289",
  "New legats and funders improvement 290",
  "New legats and funders improvement 291",
  "New legats and funders improvement 292",
  "New legats and funders improvement 293",
  "New legats and funders improvement 294",
  "New legats and funders improvement 295",
  "New legats and funders improvement 296",
  "New legats and funders improvement 297",
  "New legats and funders improvement 298",
  "New legats and funders improvement 299",
  "New legats and funders improvement 300",
  # M i18n a11y 301-320
  "i18n a11y perf security improvement 301",
  "i18n a11y perf security improvement 302",
  "i18n a11y perf security improvement 303",
  "i18n a11y perf security improvement 304",
  "i18n a11y perf security improvement 305",
  "i18n a11y perf security improvement 306",
  "i18n a11y perf security improvement 307",
  "i18n a11y perf security improvement 308",
  "i18n a11y perf security improvement 309",
  "i18n a11y perf security improvement 310",
  "i18n a11y perf security improvement 311",
  "i18n a11y perf security improvement 312",
  "i18n a11y perf security improvement 313",
  "i18n a11y perf security improvement 314",
  "i18n a11y perf security improvement 315",
  "i18n a11y perf security improvement 316",
  "i18n a11y perf security improvement 317",
  "i18n a11y perf security improvement 318",
  "i18n a11y perf security improvement 319",
  "i18n a11y perf security improvement 320",
].freeze

raise "expected 320 titles, got #{TITLES.size}" unless TITLES.size == 320

out = File.expand_path("improvement_titles.txt", __dir__)
File.write(out, TITLES.join("\n") + "\n")
puts "wrote #{out} (#{TITLES.size} titles)"