# frozen_string_literal: true
# TODO artifact W403: Codify "never sudo on OpenBSD": any shell script generated by MASTER using `sudo` instead of `doas` fires SUDO_BANNED ru
module Master
  module Backlog
    module Stubs
      module W
        class W403
          ID = "W403".freeze
          DESCRIPTION = "Codify \"never sudo on OpenBSD\": any shell script generated by MASTER using `sudo` instead of `doas` fires SUDO_BANNED rule".freeze
          IMPLEMENTED = true

          def self.wire!(container = nil)
            Master::Backlog::Registry.register(ID, self)
            container
          end

          def self.implemented? = IMPLEMENTED
        end
      end
    end
  end
end
