authority letsencrypt {
api url "https://acme-v02.api.letsencrypt.org/directory"
account key "/etc/acme/letsencrypt_privkey.pem"
}

domain brgen.no {
alternative names { tv.brgen.no dating.brgen.no playlist.brgen.no takeaway.brgen.no markedsplass.brgen.no }
domain key "/etc/ssl/private/brgen.no.key"
domain certificate "/etc/ssl/brgen.no.crt"
domain chain certificate "/etc/ssl/brgen.no.chain.pem"
domain full chain certificate "/etc/ssl/brgen.no.fullchain.pem"
sign with letsencrypt
}

domain amber.brgen.no {
domain key "/etc/ssl/private/amber.brgen.no.key"
domain certificate "/etc/ssl/amber.brgen.no.crt"
domain chain certificate "/etc/ssl/amber.brgen.no.chain.pem"
domain full chain certificate "/etc/ssl/amber.brgen.no.fullchain.pem"
sign with letsencrypt
}

domain ai.brgen.no {
domain key "/etc/ssl/private/ai.brgen.no.key"
domain certificate "/etc/ssl/ai.brgen.no.crt"
domain chain certificate "/etc/ssl/ai.brgen.no.chain.pem"
domain full chain certificate "/etc/ssl/ai.brgen.no.fullchain.pem"
sign with letsencrypt
}

domain hjerterom.no {
domain key "/etc/ssl/private/hjerterom.no.key"
domain certificate "/etc/ssl/hjerterom.no.crt"
domain chain certificate "/etc/ssl/hjerterom.no.chain.pem"
domain full chain certificate "/etc/ssl/hjerterom.no.fullchain.pem"
sign with letsencrypt
}

domain bsdports.org {
domain key "/etc/ssl/private/bsdports.org.key"
domain certificate "/etc/ssl/bsdports.org.crt"
domain chain certificate "/etc/ssl/bsdports.org.chain.pem"
domain full chain certificate "/etc/ssl/bsdports.org.fullchain.pem"
sign with letsencrypt
}

domain amberapp.com {
domain key "/etc/ssl/private/amberapp.com.key"
domain certificate "/etc/ssl/amberapp.com.crt"
domain chain certificate "/etc/ssl/amberapp.com.chain.pem"
domain full chain certificate "/etc/ssl/amberapp.com.fullchain.pem"
sign with letsencrypt
}
