# frozen_string_literal: true
require "json"
require "digest"
require "fileutils"

module Master
  module Git
    class SmartHooks
      CACHE_DIR = "var/cache"
      CACHE_FILE = "file_hashes.json"
      HOOK_PATH = ".git/hooks/pre-commit"
      
      attr_reader :cache
      
      def initialize(root_path = nil)
        @root_path = root_path || Dir.pwd
        @cache_path = File.join(@root_path, CACHE_DIR, CACHE_FILE)
        @cache = load_cache
        ensure_cache_dir
      end
      
      # Install pre-commit hook
      def install
        template_path = File.join(Master::ROOT, "lib", "git", "hook_templates", "pre-commit.sh")
        hook_path = File.join(@root_path, HOOK_PATH)
        
        # Read template
        unless File.exist?(template_path)
          return Result.err("Hook template not found: #{template_path}")
        end
        
        template = File.read(template_path)
        
        # Replace placeholder with actual path
        master_path = File.join(Master::ROOT, "bin", "cli")
        hook_content = template.gsub("%{master_cli_path}", master_path)
        
        # Write hook
        File.write(hook_path, hook_content)
        File.chmod(0755, hook_path)
        
        Result.ok(message: "Pre-commit hook installed at #{hook_path}")
      rescue => e
        Result.err("Failed to install hook: #{e.message}")
      end
      
      # Uninstall pre-commit hook
      def uninstall
        hook_path = File.join(@root_path, HOOK_PATH)
        
        if File.exist?(hook_path)
          content = File.read(hook_path)
          if content.include?("Generated by MASTER CLI")
            File.delete(hook_path)
            Result.ok(message: "Pre-commit hook removed")
          else
            Result.err("Hook exists but wasn't created by MASTER")
          end
        else
          Result.ok(message: "No pre-commit hook found")
        end
      rescue => e
        Result.err("Failed to uninstall hook: #{e.message}")
      end
      
      # Test hook on staged files
      def test(dry_run: true)
        staged_files = get_staged_files
        
        if staged_files.empty?
          return Result.ok(message: "No staged files to analyze")
        end
        
        puts "Staged files: #{staged_files.size}"
        staged_files.each { |f| puts "  - #{f}" }
        
        # Analyze each file
        results = staged_files.map do |file|
          analyze_with_cache(file, dry_run: dry_run)
        end
        
        violations = results.sum { |r| r[:violations]&.size || 0 }
        
        Result.ok(
          files: staged_files.size,
          violations: violations,
          cached: results.count { |r| r[:cached] }
        )
      end
      
      # Analyze a file with caching
      def analyze_with_cache(file, dry_run: false)
        return { cached: false, violations: [] } unless File.exist?(file)
        
        content = File.read(file)
        file_hash = Digest::SHA256.hexdigest(content)
        
        # Check cache
        if @cache[file] && @cache[file]["sha256"] == file_hash
          puts "  ✓ #{file} (cached)" unless dry_run
          return {
            cached: true,
            violations: @cache[file]["violations"],
            score: @cache[file]["score"]
          }
        end
        
        # Analyze with engine
        engine = Master::Engine.new(
          principles: Boot.run,
          llm: Master::LLM.new(principles: Boot.run)
        )
        
        result = engine.scan(file)
        
        if result.ok?
          violations = result.value[:issues] || []
          score = calculate_score(violations)
          
          # Update cache
          @cache[file] = {
            "sha256" => file_hash,
            "last_scan" => Time.now.utc.iso8601,
            "violations" => violations,
            "score" => score
          }
          save_cache
          
          puts "  ✓ #{file} (analyzed, score: #{score})" unless dry_run
          
          {
            cached: false,
            violations: violations,
            score: score
          }
        else
          { cached: false, violations: [] }
        end
      end
      
      # Get list of staged Ruby files
      def get_staged_files
        return [] unless Dir.exist?(File.join(@root_path, ".git"))
        
        output = `cd #{@root_path} && git diff --cached --name-only --diff-filter=ACM 2>/dev/null`
        return [] unless $?.success?
        
        output.split("\n")
              .select { |f| f.end_with?(".rb") }
              .map { |f| File.join(@root_path, f) }
              .select { |f| File.exist?(f) }
      end
      
      # Clear cache
      def clear_cache
        @cache = {}
        save_cache
        Result.ok(message: "Cache cleared")
      end
      
      private
      
      def ensure_cache_dir
        dir = File.dirname(@cache_path)
        FileUtils.mkdir_p(dir) unless Dir.exist?(dir)
      rescue Errno::EACCES
        # Can't create cache dir
      end
      
      def load_cache
        return {} unless File.exist?(@cache_path)
        JSON.parse(File.read(@cache_path))
      rescue JSON::ParserError, Errno::ENOENT
        {}
      end
      
      def save_cache
        File.write(@cache_path, JSON.pretty_generate(@cache))
      rescue Errno::EACCES
        # Can't write cache
      end
      
      def calculate_score(violations)
        return 100 if violations.empty?
        [100 - (violations.size * 5), 0].max
      end
    end
  end
end
