#!/usr/bin/env ruby
# frozen_string_literal: true

root = File.expand_path("../..", __dir__)
ruby = ENV.fetch("RUBY", "ruby")

commands = [
  [ruby, File.join(root, "OPENBSD", "gates", "verify_deploy_identity.rb")],
  [ruby, File.join(root, "RAILS", "gates", "runner.rb"), "domain_alignment"],
]

commands.each do |cmd|
  unit = "verify#{commands.index(cmd) || 0}"
  Master::Trace::Dmesg.attach(unit, "verify0", cmd.join(" "))
  system(*cmd) or exit($?.exitstatus || 1)
end

Master::Trace::Dmesg.status("verify0", "passed")
