# frozen_string_literal: true

# Shared importmap pins for the pub4 Rails family.
# Include from each app: eval(File.read(Shared::Engine.root.join("config/importmap_baseline.rb")), binding)

pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "@hotwired--stimulus.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "@rails/request.js", to: "@rails--request.js.js"
pin "stimulus-use"
pin "stimulus_reflex"
pin "cable_ready"
pin "@stimulus_reflex/futurism"
pin "date-fns"
pin "sortablejs"
pin "pub4/hotwire", to: "pub4_hotwire.js"
pin "pub4/stimulus_boot", to: "pub4_stimulus_boot.js"
pin "pub4/live_search", to: "pub4_live_search_controller.js"
pin "pub4/offline_page", to: "pub4_offline_page_controller.js"
pin "pub4/install_prompt", to: "pub4_install_prompt_controller.js"
pin "pub4/nav_reveal", to: "pub4_nav_reveal.js"
pin "pub4/infinite_scroll", to: "pub4_infinite_scroll_controller.js"
pin "pub4/browser_fingerprint", to: "pub4_browser_fingerprint_controller.js"
pin "pub4/theme_meta", to: "pub4_theme_meta.js"
pin "pub4/theme_toggle", to: "pub4_theme_toggle_controller.js"
pin "pub4/minimal_gesture", to: "minimal-gesture.js"

pin "@stimulus-components/auto-submit", to: "@stimulus-components--auto-submit.js"
pin "@stimulus-components/character-counter", to: "@stimulus-components--character-counter.js"
pin "@stimulus-components/checkbox-select-all", to: "@stimulus-components--checkbox-select-all.js"
pin "@stimulus-components/clipboard", to: "@stimulus-components--clipboard.js"
pin "@stimulus-components/content-loader", to: "@stimulus-components--content-loader.js"
pin "@stimulus-components/dialog", to: "@stimulus-components--dialog.js"
pin "@stimulus-components/dropdown", to: "@stimulus-components--dropdown.js"
pin "@stimulus-components/hotkey", to: "@stimulus-components--hotkey.js"
pin "@stimulus-components/lightbox", to: "@stimulus-components--lightbox.js"
pin "@stimulus-components/notification", to: "@stimulus-components--notification.js"
pin "@stimulus-components/popover", to: "@stimulus-components--popover.js"
pin "@stimulus-components/read-more", to: "@stimulus-components--read-more.js"
pin "@stimulus-components/reveal", to: "@stimulus-components--reveal.js"
pin "@stimulus-components/scroll-to", to: "@stimulus-components--scroll-to.js"
pin "@stimulus-components/sortable", to: "@stimulus-components--sortable.js"
pin "@stimulus-components/sound", to: "@stimulus-components--sound.js"
pin "@stimulus-components/speech-recognition", to: "@stimulus-components--speech-recognition.js"
pin "@stimulus-components/textarea-autogrow", to: "@stimulus-components--textarea-autogrow.js"
pin "@stimulus-components/timeago", to: "@stimulus-components--timeago.js"
pin "@stimulus-components/animated-number", to: "@stimulus-components--animated-number.js"
pin "@stimulus-components/password-visibility", to: "@stimulus-components--password-visibility.js"
pin "@stimulus-components/rails-nested-form", to: "@stimulus-components--rails-nested-form.js"
pin "@stimulus-components/carousel", to: "@stimulus-components--carousel.js"