# frozen_string_literal: true

require "json"
require "yaml"
require_relative "../../tools/generate_route_manifest"

module Deploy
  # Canonical inventory of full-page Rails surfaces for UI/UX simulation.
  # Discovers non-partial HTML views under brgen, amber, and MASTER web, then
  # maps each to a host + path + guest/auth persona.
  module PageInventory
    ROOT = File.expand_path("../../..", __dir__)
    APEX = "brgen.no"
    VERTICAL_HOSTS = {
      "dating" => "dating.#{APEX}",
      "marketplace" => "markedsplass.#{APEX}",
      "playlist" => "playlist.#{APEX}",
      "tv" => "tv.#{APEX}",
      "takeaway" => "takeaway.#{APEX}",
      "maps" => "maps.#{APEX}",
    }.freeze

    APPS = {
      "brgen" => {
        views: File.join(ROOT, "RAILS", "brgen", "app", "views"),
        port_key: "brgen",
      },
      "amber" => {
        views: File.join(ROOT, "RAILS", "amber", "app", "views"),
        port_key: "amber",
      },
      "bsdports" => {
        views: File.join(ROOT, "RAILS", "bsdports", "app", "views"),
        port_key: "bsdports",
      },
      "master" => {
        views: nil, # special-cased
        port_key: "master",
      },
    }.freeze

    SHARED_ROOT = File.join(ROOT, "RAILS", "shared", "app", "views")

    # brgen's five verticals became mountable engines, and the discovery below
    # only ever walked RAILS/brgen/app/views -- so 57 full-page vertical views
    # left the simulation without anything reporting it. The vertical branch of
    # brgen_route kept working on parts that no longer arrived.
    ENGINE_VIEWS = Dir.glob(File.join(ROOT, "RAILS", "brgen", "engines", "*", "app", "views")).sort.freeze

    # controller#action -> GET paths, generated by tools/generate_route_manifest.rb.
    # Routes are the source of truth for a page's URL; the *_route ladders below
    # are the fallback for a view whose action has no GET route of its own.
    MANIFEST_PATH = File.join(ROOT, "RAILS", "gates", "data", "route_manifest.yml")

    # Pages the engine renders inside every host app. Their routes come from
    # shared/config/routes/{auth,social}.rb, so no filename convention yields them.
    # uncovered_shared_views fails the simulation when a new one lands without a row.
    SHARED_PAGES = {
      %w[account_settings show] => { path: "/account", persona: "auth" },
      %w[two_factor_setups show] => { path: "/two_factor_setup", persona: "auth" },
      %w[passwords new] => { path: "/passwords/new", persona: "guest" },
      %w[passwords edit] => { path: "/passwords/:token/edit", persona: "guest", needs_id: true },
      # bsdports keeps the social routes behind BSDPORTS_SOCIAL=1.
      %w[notifications index] => { path: "/notifications", persona: "auth", apps: %w[brgen amber] },
      %w[pages privacy] => { path: "/privacy", persona: "guest" }, %w[pages terms] => { path: "/terms", persona: "guest" }, %w[pages cookies] => { path: "/cookies", persona: "guest" },
    }.freeze

    # Rendered by MasterGuestHome inside each app's own home action, so the home row covers it.
    SHARED_VIEWS_WITHOUT_ROUTE = [%w[shared master_guest]].freeze

    # These live under an app's `shared/` directory so controllers can render
    # them as error templates. They are not controller actions, and inventing a
    # URL from their filename makes the live probe report a 404 for a route that
    # must not exist.
    MASTER_PAGES = [
      { id: "master/face", view: "MASTER/web/app/views/chat/index.html.erb", path: "/", persona: "guest" },
      { id: "master/dashboard", view: "MASTER/web/app/views/dashboard/index.html.erb", path: "/dashboard", persona: "guest" },
      { id: "master/offline", view: "MASTER/web/public/offline.html", path: "/offline.html", persona: "guest" },
      { id: "master/diag", view: "MASTER/web/public/diag.html", path: "/diag.html", persona: "guest" },
      { id: "master/swarm", view: "MASTER/web/public/swarm.html", path: "/swarm.html", persona: "guest" },
    ].freeze

    # Guest-open bsdports catalogue paths (family completeness — CRT dialect).
    BSDPORTS_LIVE = [
      { id: "bsdports/home", path: "/", persona: "guest" },
      { id: "bsdports/ports", path: "/ports", persona: "guest" },
      { id: "bsdports/categories", path: "/categories", persona: "guest" },
      { id: "bsdports/maintainers", path: "/maintainers", persona: "guest" }, { id: "bsdports/session", path: "/session/new", persona: "guest" },
    ].freeze

    module_function

    def all
      brgen_pages + brgen_engine_pages + amber_pages + bsdports_pages + shared_pages + master_pages
    end

    def manifest
      @manifest ||= File.file?(MANIFEST_PATH) ? (YAML.safe_load_file(MANIFEST_PATH) || {}) : {}
    end

    def route_table(app)
      manifest.dig("apps", app, "routes") || {}
    end

    # A manifest that no longer matches the routes it was generated from is worse
    # than no manifest: it resolves confidently and wrongly. page_simulation
    # reports this so regenerating stays a step someone takes, not one they forget.
    def stale_route_manifests
      (manifest["apps"] || {}).filter_map do |app, row|
        live = RouteManifest.digest(app)
        next if live == row["digest"]

        "route_manifest: #{app} digest #{row['digest']} != #{live} — " \
          "run `ruby RAILS/tools/generate_route_manifest.rb #{app}`"
      end
    rescue StandardError => e
      ["route_manifest: digest check failed (#{e.class}: #{e.message})"]
    end

    # Rails' own convention: every part but the last names the controller.
    def manifest_route(app, parts)
      return nil if parts.size < 2

      route_table(app)["#{parts[0..-2].join('/')}##{parts[-1]}"]&.first
    end

    def brgen_engine_pages
      ENGINE_VIEWS.flat_map do |root|
        discover(root).filter_map do |abs|
          parts = relative_parts(abs, root)
          next if mailer_parts?(parts)

          host, path, action = brgen_route(parts)
          next unless path

          rel = parts.join("/")
          {
            id: "brgen/#{rel}",
            app: "brgen",
            view: abs.sub("#{ROOT}/", ""),
            abs_view: abs,
            host: host,
            path: path,
            action: action,
            persona: guest_open_brgen?(path, rel) ? "guest" : "auth",
            needs_id: path.match?(/:\w+/),
          }
        end
      end
    end

    # One row per host app, because the engine's view is a different page in each
    # — and an app keeping its own copy of a shared view renders that copy, so the
    # row must grade the file Rails resolves, not the shared original underneath.
    def shared_pages
      SHARED_PAGES.flat_map do |parts, row|
        shared_abs = File.join(SHARED_ROOT, "#{parts.join("/")}.html.erb")
        Array(row[:apps] || %w[brgen amber bsdports]).map do |app|
          abs = app_override(app, parts) || shared_abs
          {
            id: "#{app}/shared/#{parts.join("/")}",
            app: app,
            view: abs.sub("#{ROOT}/", ""),
            abs_view: abs,
            host: nil,
            path: row[:path],
            action: parts.last,
            persona: row[:persona],
            needs_id: row.fetch(:needs_id, false),
          }
        end
      end
    end

    # The app-local copy Rails renders in preference to the shared engine view.
    def app_override(app, parts)
      candidate = File.join(ROOT, "RAILS", app, "app", "views", "#{parts.join("/")}.html.erb")
      candidate if File.exist?(candidate)
    end

    # A shared page nobody declared is a page no simulation ever loads — which is how
    # /account/export and /notifications both reached production answering 500.
    def uncovered_shared_views
      declared = SHARED_PAGES.keys + SHARED_VIEWS_WITHOUT_ROUTE
      discover(SHARED_ROOT).filter_map do |abs|
        parts = relative_parts(abs, SHARED_ROOT)
        next if mailer_parts?(parts) || declared.include?(parts)

        abs.sub("#{ROOT}/", "")
      end
    end

    def guest_liveable
      all.select { |p| p[:persona] == "guest" && !p[:needs_id] && !mailer?(p) }
    end

    def brgen_pages
      root = APPS["brgen"][:views]
      discover(root).filter_map do |abs|
        parts = relative_parts(abs, root)
        next if mailer_parts?(parts)

        host, path, action = brgen_route(parts)
        next unless path

        rel = parts.join("/")
        {
          id: "brgen/#{rel}",
          app: "brgen",
          view: abs.sub("#{ROOT}/", ""),
          abs_view: abs,
          host: host,
          path: path,
          action: action,
          persona: guest_open_brgen?(path, rel) ? "guest" : "auth",
          needs_id: path.match?(/:\w+/),
        }
      end
    end

    def amber_pages
      root = APPS["amber"][:views]
      discover(root).filter_map do |abs|
        parts = relative_parts(abs, root)
        path, action = amber_route(parts)
        next unless path

        rel = parts.join("/")
        {
          id: "amber/#{rel}",
          app: "amber",
          view: abs.sub("#{ROOT}/", ""),
          abs_view: abs,
          host: nil,
          path: path,
          action: action,
          persona: guest_open_amber?(path, rel) ? "guest" : "auth",
          needs_id: path.match?(/:\w+/),
        }
      end
    end

    def master_pages
      MASTER_PAGES.map do |row|
        abs = File.join(ROOT, row[:view])
        {
          id: row[:id],
          app: "master",
          view: row[:view],
          abs_view: abs,
          host: nil,
          path: row[:path],
          action: "show",
          persona: row[:persona],
          needs_id: false,
        }
      end
    end

    def bsdports_pages
      root = APPS["bsdports"][:views]
      return BSDPORTS_LIVE.map { |row| bsdports_live_row(row) } unless File.directory?(root)

      discovered = discover(root).filter_map do |abs|
        parts = relative_parts(abs, root)
        path, action = bsdports_route(parts)
        next unless path

        rel = parts.join("/")
        {
          id: "bsdports/#{rel}",
          app: "bsdports",
          view: abs.sub("#{ROOT}/", ""),
          abs_view: abs,
          host: nil,
          path: path,
          action: action,
          persona: path.end_with?("/edit") ? "auth" : "guest",
          needs_id: path.match?(/:\w+/),
        }
      end
      discovered
    end

    def bsdports_live_row(row)
      {
        id: row[:id],
        app: "bsdports",
        view: "RAILS/bsdports/app/views",
        abs_view: File.join(ROOT, "RAILS", "bsdports", "app", "views", "ports", "index.html.erb"),
        host: nil,
        path: row[:path],
        action: "index",
        persona: row[:persona],
        needs_id: false,
      }
    end

    # The manifest or nothing. A view it does not answer has no GET route --
    # that is what `rails routes` said when the manifest was generated -- so it
    # is not a page, and inventing a URL for one is what sent page_simulation
    # at 404s in the first place.
    def bsdports_route(parts)
      resolved = manifest_route("bsdports", parts)
      [resolved, parts[-1]] if resolved
    end

    def discover(root)
      Dir.glob(File.join(root, "**", "*.html.erb")).sort.reject do |path|
        base = File.basename(path)
        base.start_with?("_") || path.include?("/layouts/")
      end
    end

    def relative_parts(abs, root)
      rel = abs.sub(%r{\A#{Regexp.escape(root)}/?}, "")
      rel = rel.sub(/\.html\.erb\z/, "")
      rel.split("/")
    end

    def mailer_parts?(parts)
      parts.any? { |p| p.end_with?("_mailer") || p == "mailer" }
    end

    def mailer?(page)
      page[:view].to_s.include?("_mailer") || page[:view].to_s.include?("/mailer/")
    end

    def brgen_route(parts)
      resolved = manifest_route("brgen", parts)
      [VERTICAL_HOSTS.fetch(parts[0], APEX), resolved, parts[-1]] if resolved
    end

    def amber_route(parts)
      resolved = manifest_route("amber", parts)
      [resolved, parts[-1]] if resolved
    end

    # Sign-in and sign-up are the only authoring forms a guest reaches.
    GUEST_AUTHORING_PATHS = %w[/session/new /registration/new /passwords/new].freeze

    def guest_open_brgen?(path, rel)
      return false if rel.match?(%r{\Aadmin/|activity_events|notifications|saved_searches|matches|profiles/edit|orders/})
      return false if path.end_with?("/edit")
      # Nested create forms need a channel/resource id — not guest-liveable as bare paths
      return false if path.include?("/channels/:slug/")
      return true if GUEST_AUTHORING_PATHS.include?(path)
      # This predicate defaults to guest, which held while the inventory was 43
      # app-level views. The 57 engine views brought a `new` form per vertical;
      # each answers 403 to a guest, so every one was reported as a broken page.
      return false if path.end_with?("/new")

      true
    end

    def guest_open_amber?(path, _rel)
      open_exact = %w[/ /items /demo /posts /posts/feed /session/new /registration/new /outfits /passwords/new]
      return true if open_exact.include?(path)
      return true if path.start_with?("/demo") || path.start_with?("/ai/")
      return false if path.end_with?("/edit") || path.include?("/new")
      # Default browse indexes that still need session are auth
      %w[/connections /declutter /live_streams /messages /planned_outfits /wardrobe_items /items/shopping_list].include?(path) ? false : false
    end

    def write_snapshot!(path = File.join(ROOT, "RAILS", "gates", "data", "page_sim_inventory.yml"))
      rows = all.map do |p|
        p.except(:abs_view).transform_keys(&:to_s)
      end
      File.write(path, {
        "generated_note" => "Snapshot of Deploy::PageInventory.all — regenerate via page_simulation gate",
        "count" => rows.size,
        "pages" => rows,
      }.to_yaml)
      path
    end
  end
end
