#!/usr/bin/env zsh
# Stage 1 of OPENBSD/OPERATOR.sh: DNS, DNSSEC and TLS.
#
# This file is sourced by OPERATOR.sh after its shared helpers and deploy facts
# are loaded. It owns stage_1 only; it does not execute on source.


stage_1() {
  log INFO "Stage 1: DNS and certificates"

  typeset -a _df_root; _df_root=("${(@f)$(df -k /)}"); typeset _root_avail=${${(z)_df_root[2]}[4]}
  (( _root_avail < 10000 )) && { log ERROR "Insufficient disk space on /"; exit 1 }
  typeset -a _df_var; _df_var=("${(@f)$(df -k /var)}"); typeset _var_avail=${${(z)_df_var[2]}[4]}
  (( _var_avail < 512000 )) && { log ERROR "Insufficient disk space on /var"; exit 1 }

  # ffmpeg is required, not optional: lib/voice/engines.rb gates concat_mp3 and
  # the WAV->MP3 conversion on `ffmpeg?` and returns *quietly* when it is absent.
  # Without it TTS produced un-concatenated or unconverted audio on the VPS with
  # no error anywhere — working on a Mac and silently degrading in production,
  # which is the worst failure shape. See TODO.md "Host TTS Binaries".
  pkg_add -U ldns-utils ruby%3.4 zap zsh fish neovim tmux fontconfig fzf ripgrep fd espeak ffmpeg 2>/var/log/pkg_add.log \
    || { log ERROR "pkg_add failed. See /var/log/pkg_add.log"; exit 1 }

  [[ -f /etc/rc.conf.local && $(<"/etc/rc.conf.local") == *"pf=NO"* ]] && log WARN "pf disabled in rc.conf.local"
  ifconfig vio0 >/dev/null 2>&1 || { log ERROR "Interface vio0 not found"; exit 1 }

  /sbin/pfctl -d || log WARN "pf disable failed"
  /sbin/pfctl -e || { log ERROR "pf enable failed"; exit 1 }
  install_static etc/pf.stage1.conf /etc/pf.conf
  /sbin/pfctl -nf /etc/pf.conf || { log ERROR "pf.conf invalid"; exit 1 }
  /sbin/pfctl -f /etc/pf.conf  || { log ERROR "pf failed"; exit 1 }

  [[ -d /var/nsd/etc ]]          || { log ERROR "/var/nsd/etc missing"; exit 1 }
  [[ -d /var/nsd/zones/master ]] || { log ERROR "/var/nsd/zones/master missing"; exit 1 }

  backup_directory /var/nsd/zones/master nsd-zones || { log ERROR "Backup failed"; exit 1 }
  transaction_log "DELETE" "/var/nsd/etc/*" "START"
  rm -rf /var/nsd/etc/*(/) /var/nsd/zones/master/*(/) # scan: intentional — backed up above, bracketed by transaction_log DELETE
  transaction_log "DELETE" "/var/nsd/etc/* and /var/nsd/zones/master/*" "SUCCESS"

  # nsd.conf and every zone file are generated by bin/render_dns.rb and committed,
  # so this installs them rather than rebuilding them from a template per domain.
  # The old loop was the third writer of the same records and disagreed with the
  # other two: it emitted no www, no CAA, no SPF, no DMARC and an MX pointing at
  # a mail server that exists for one domain out of sixty.
  install_static var/nsd/etc/nsd.conf /var/nsd/etc/nsd.conf
  nsd-checkconf /var/nsd/etc/nsd.conf || { log ERROR "nsd.conf invalid"; exit 1 }

  cp ${CONFIG_ROOT}/var/nsd/zones/master/*.zone /var/nsd/zones/master/

  for domain_entry in $ALL_DOMAINS; do
    typeset domain=${domain_entry%%:*}
    typeset zonefile=/var/nsd/zones/master/$domain.zone

    [[ -f $zonefile ]] || { log ERROR "No generated zone for $domain — run bin/render_dns.rb"; exit 1 }
    nsd-checkzone "$domain" "$zonefile" || { log ERROR "Zone invalid for $domain"; exit 1 }

    # Keys only when the zone has none.
    #
    # This unconditionally ran ldns-keygen twice per domain per invocation and
    # never removed anything, so every re-run added a KSK and a ZSK to each zone
    # and the old ones stayed published — ldns-signzone signs with every key it
    # is handed. Measured 2026-08-12: 700 key files for 60 zones, and 407 .ds
    # files naming keys that had long since been superseded.
    #
    # Regenerating a KSK is not a harmless extra file once a DS record is
    # published. The DS at the registrar names one key by tag; sign with a new
    # KSK and every validating resolver SERVFAILs the entire zone until the
    # registrar catches up. So the rule is: generate only what is missing, and
    # rotate deliberately, never as a side effect of re-running the installer.
    typeset -a existing
    existing=(/var/nsd/zones/master/K${domain}.+*.key(N))
    if (( ${#existing} == 0 )); then
      log INFO "generating DNSSEC keys for $domain"
      ( cd /var/nsd/zones/master && ldns-keygen -a ECDSAP256SHA256 "$domain" >/dev/null )
      ( cd /var/nsd/zones/master && ldns-keygen -k -a ECDSAP256SHA256 "$domain" >/dev/null )
    fi
  done

  chown _nsd:_nsd /var/nsd/zones/master/*
  chmod 640 /var/nsd/zones/master/*

  # One signing implementation, not two. nsd-resign is what runs every night; if
  # it can sign the fleet, so can a first install, and there is no second code
  # path to drift. It also picks exactly one KSK and one ZSK per zone, which is
  # the behaviour the loop above was missing.
  ruby /usr/local/bin/nsd-resign --force || { log ERROR "zone signing failed"; exit 1 }

  for domain_entry in $ALL_DOMAINS; do
    typeset domain=${domain_entry%%:*}
    nsd-checkzone "$domain" /var/nsd/zones/master/$domain.zone.signed \
      || { log ERROR "Signed zone invalid for $domain"; exit 1 }
  done

  # DS records are derived from the signed zone by bin/ds-records, never written
  # to a .ds file here. A cached DS goes stale the moment a key rotates, and a DS
  # naming a key the zone no longer publishes takes the zone down.
  log INFO "DS records: doas ruby34 ${REPO_ROOT}/OPENBSD/bin/ds-records"

  [[ ! -f /var/nsd/etc/nsd_server.pem ]] && {
    log INFO "Generating NSD control certificates"
    cd /var/nsd/etc && nsd-control-setup || { log ERROR "nsd-control-setup failed"; exit 1 }
  }

  cleanup_nsd
  /usr/sbin/rcctl enable nsd

  typeset retries=0 max_retries=2
  while (( retries <= max_retries )); do
    /usr/bin/timeout 10 /usr/sbin/rcctl start nsd && break
    (( retries++ ))
    (( retries <= max_retries )) && cleanup_nsd || { log ERROR "nsd failed"; exit 1 }
  done

  sleep 5
  typeset _nsd_check; _nsd_check=$(/usr/sbin/rcctl check nsd)
  [[ $_nsd_check == *"nsd(ok)"* ]] || { log ERROR "nsd not running"; exit 1 }
  verify_nsd

  [[ -d /var/www/acme ]] || mkdir -p /var/www/acme
  install_static etc/httpd.conf /etc/httpd.conf
  httpd -n -f /etc/httpd.conf || { log ERROR "httpd.conf invalid"; exit 1 }
  /usr/sbin/rcctl enable httpd
  /usr/sbin/rcctl start httpd || { log ERROR "httpd failed"; exit 1 }
  sleep 5
  typeset _httpd_check; _httpd_check=$(/usr/sbin/rcctl check httpd)
  [[ $_httpd_check == *"httpd(ok)"* ]] || { log ERROR "httpd not running"; exit 1 }

  # httpd strips /.well-known/acme-challenge/ and serves from /var/www/acme/<token>
  print -r -- test > /var/www/acme/test
  typeset http_status=${$(curl -s -o /dev/null -w "%{http_code}" http://$BRGEN_IP/.well-known/acme-challenge/test):-000}
  rm -f /var/www/acme/test
  [[ $http_status == "200" ]] || { log ERROR "httpd pre-flight failed (HTTP $http_status)"; exit 1 }

  [[ $(<"/etc/group") == *$'\n_acme:'* || $(<"/etc/group") == _acme:* ]] || groupadd -g 765 _acme
  [[ ! -f /etc/acme/letsencrypt_privkey.pem ]] && \
    openssl genpkey -algorithm RSA -out /etc/acme/letsencrypt_privkey.pem -pkeyopt rsa_keygen_bits:4096
  chown root:_acme /etc/acme/letsencrypt_privkey.pem
  chmod 640 /etc/acme/letsencrypt_privkey.pem

  install_static etc/acme-client.conf /etc/acme-client.conf
  acme-client -n -f /etc/acme-client.conf || { log ERROR "acme-client.conf invalid"; exit 1 }

  for domain_entry in $ALL_DOMAINS; do
    typeset domain=${domain_entry%%:*}
    typeset dns_check=${$(/usr/bin/dig @"$BRGEN_IP" "$domain" A +short):-}
    if [[ $dns_check != $BRGEN_IP ]]; then
      log WARN "DNS for $domain failed"; FAILED_CERTS[$domain]=1; continue
    fi
    print -r -- "test_$domain" > /var/www/acme/test_$domain
    typeset http_status=${$(curl -s -o /dev/null -w "%{http_code}" -H "Host: $domain" http://$BRGEN_IP/.well-known/acme-challenge/test_$domain):-000}
    rm -f /var/www/acme/test_$domain
    if [[ $http_status != 200 ]]; then
      log WARN "HTTP test for $domain failed"; FAILED_CERTS[$domain]=1; continue
    fi
    if acme-client -v -f /etc/acme-client.conf "$domain"; then
      generate_tlsa_record "$domain"
    else
      log WARN "Certificate issuance failed for $domain"; FAILED_CERTS[$domain]=1
    fi
  done
  (( $#FAILED_CERTS )) && retry_failed_certs

  install_static usr/local/bin/renew-certs.sh /usr/local/bin/renew-certs.sh
  chmod 755 /usr/local/bin/renew-certs.sh
  install_static usr/local/bin/uptime-check.sh /usr/local/bin/uptime-check.sh
  chmod 755 /usr/local/bin/uptime-check.sh
  install_tracked_crontab || exit 1

  log INFO "Stage 1 complete. ns.brgen.no ($BRGEN_IP) authoritative with DNSSEC."
  log INFO "DS records: doas ruby34 ${REPO_ROOT}/OPENBSD/bin/ds-records — submit each to your registrar (Domeneshop: domain settings → DNSSEC)."
  log INFO "Only for domains the registrar has actually delegated to ns.brgen.no. A DS on a domain we do not serve takes it down."
  log INFO "After submitting DS records, wait 24-48h for propagation, then press Enter to continue."
  log INFO "Verify with: dig DS brgen.no +short"
  read -r
}
