# frozen_string_literal: true

namespace :assets do
  desc "Build public/face.runtime.js as a small local loader for the authoritative face sources"
  task build_face_runtime: :environment do
    out = Rails.root.join("public/face.runtime.js")
    segments = (1..3).map { |part| "face.part#{part}.txt" }
    segments << "face_speech_runtime.js"
    segments << "face_speech_playback.js"
    segments << "face.part5.txt"

    segments.each do |name|
      path = Rails.root.join("public", name)
      raise "missing #{path}" unless File.file?(path)
    end

    source = [
      "// Generated by rails assets:build_face_runtime — do not edit by hand.",
      "// Import map + MASTER_ASSET_PATHS resolve tail module imports at runtime.",
      "const FACE_RUNTIME_SOURCES = #{segments.inspect};",
      'const FACE_RUNTIME_URL = (name) => new URL(name, document.baseURI).href;',
      'const FACE_RUNTIME_FETCH = (name) => fetch(FACE_RUNTIME_URL(name), { cache: "force-cache" }).then((response) => {',
      '  if (!response.ok) throw new Error("failed to load face source " + name + ": " + response.status);',
      "  return response.text();",
      "});",
      'const FACE_RUNTIME_SOURCE_BLOB = await Promise.all(FACE_RUNTIME_SOURCES.map(FACE_RUNTIME_FETCH)).then((sources) => new Blob([sources.join("\\n")], { type: "text/javascript" }));',
      "const FACE_RUNTIME_BLOB_URL = URL.createObjectURL(FACE_RUNTIME_SOURCE_BLOB);",
      "try {",
      "  await import(FACE_RUNTIME_BLOB_URL);",
      "} finally {",
      "  URL.revokeObjectURL(FACE_RUNTIME_BLOB_URL);",
      "}",
      "",
    ].join("\n")

    File.write(out, source)
    puts "wrote #{out} (#{File.size(out)} bytes)"
  end
end

if Rake::Task.task_defined?("assets:precompile")
  Rake::Task["assets:precompile"].enhance(["assets:build_face_runtime"])
end
