#!/usr/bin/env zsh
# @shared_functions.sh — shared helpers for DEPLOY/rails/* scripts
# Source this file; do not execute directly.

typeset -r BASE_DIR="${BASE_DIR:-/home/dev/rails}"
typeset -r APP_PORT="${APP_PORT:-3000}"

# ── Logging ──────────────────────────────────────────────────────────────────

log() {
  print -P "%F{cyan}==>%f $*"
}

log_ok() {
  print -P "%F{green}✔%f $*"
}

log_warn() {
  print -P "%F{yellow}WARN%f $*" >&2
}

log_err() {
  print -P "%F{red}ERR%f $*" >&2
}

# ── Precondition checks ───────────────────────────────────────────────────────

command_exists() {
  local cmd="$1"
  if ! command -v "$cmd" &>/dev/null; then
    log_err "Required command not found: $cmd"
    exit 1
  fi
  log_ok "$cmd found"
}

# check_app_exists APP_NAME SENTINEL_FILE
# Returns 0 (true) if app already set up
check_app_exists() {
  local app="$1" sentinel="$2"
  local app_dir="${BASE_DIR}/${app}"
  if [[ -d "$app_dir" && -f "${app_dir}/${sentinel}" ]]; then
    log_warn "${app} already set up (${sentinel} exists). Skipping."
    return 0
  fi
  return 1
}

# ── App scaffolding ───────────────────────────────────────────────────────────

# setup_full_app APP_NAME
# Creates the Rails app under $BASE_DIR/$APP_NAME if missing
setup_full_app() {
  local app="$1"
  local app_dir="${BASE_DIR}/${app}"

  mkdir -p "$BASE_DIR"

  if [[ ! -d "$app_dir" ]]; then
    log "Creating Rails 8 app: $app"
    cd "$BASE_DIR"
    rails new "$app" --database=postgresql --skip-git --css=tailwind --javascript=esbuild
  fi

  cd "$app_dir"
  log_ok "Working in: $app_dir"
}

# ── Gem helpers ───────────────────────────────────────────────────────────────

install_gem() {
  local gem="$1"
  if ! grep -q "\"${gem}\"" Gemfile 2>/dev/null; then
    echo "gem \"${gem}\"" >> Gemfile
    bundle install --quiet
    log_ok "gem ${gem} installed"
  else
    log_ok "gem ${gem} already present"
  fi
}

# ── Asset helpers ─────────────────────────────────────────────────────────────

# generate_default_css APP_NAME — writes a minimal dark-theme SCSS
generate_default_css() {
  local app="${1:-app}"
  mkdir -p app/assets/stylesheets
  cat > app/assets/stylesheets/application.scss << 'SCSS'
/* Generated by @shared_functions.sh */
:root {
  --bg: #0a0a0a;
  --surface: #1a1a1a;
  --text: #e8eaed;
  --text-dim: #9aa0a6;
  --primary: #8ab4f8;
  --accent: #ff4500;
  --radius: 8px;
  --space: 8px;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: system-ui, -apple-system, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}
main { max-width: 1200px; margin: 0 auto; padding: calc(var(--space) * 2); }
h1 { font-size: 2rem; margin-bottom: calc(var(--space) * 2); }
h2 { font-size: 1.5rem; margin-bottom: var(--space); }
a { color: var(--primary); text-decoration: none; }
.card {
  background: var(--surface);
  border-radius: var(--radius);
  padding: calc(var(--space) * 2);
  margin-bottom: calc(var(--space) * 2);
}
@media (max-width: 768px) { main { padding: var(--space); } }
SCSS
  log_ok "default CSS written"
}

# generate_all_stimulus_controllers — writes a basic Stimulus index
generate_all_stimulus_controllers() {
  mkdir -p app/javascript/controllers
  cat > app/javascript/controllers/index.js << 'JS'
import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)
JS
  log_ok "Stimulus controllers index written"
}
