#!/usr/bin/env ruby
# frozen_string_literal: true
# Mirror live VPS config into OPENBSD/ with secret redaction.
# Run on VPS: doas ruby34 ~/pub4/OPENBSD/sync.rb

require "fileutils"
require_relative "gates/config_drift_gate"
require_relative "lib/secret_redaction"

# The files come from the drift gate, so the return leg copies exactly what the
# gate compares plus what it skips as templated. A file the gate reports drifted
# and this does not copy is a hand-edit with no way back into the repo.
#
# Two sources are this file's own. nsd.conf is generated by bin/render_dns.rb, so
# a copy of the live one makes `render_dns.rb --check` report a hand-edit on the
# box. /home/dev/.zshrc has no installer; etc/.zshrc is only this mirror of it.
#
# Zone data is not mirrored. /var/nsd/zones/master holds 61 zones, and the signed
# artifacts (*.zone.signed, K*.key, K*.ds) are regenerated on every re-sign, so a
# copy would put a churning DNS into every git diff while the nameserver remains
# the source of truth. An audit that finds signed zones or keys absent from git
# is describing this choice, not a gap. The unsigned *.zone files are different:
# bin/render_dns.rb generates them and they are committed, so --check can compare.
SOURCES = (
  VERBATIM.to_a +
  EXCLUDED.map { |repo_rel| [repo_rel, "/#{repo_rel}"] } +
  [["var/nsd/etc/nsd.conf", "/var/nsd/etc/nsd.conf"], ["etc/.zshrc", "/home/dev/.zshrc"]]
).freeze

def redact(body)
  SecretRedaction.redact(body)
end

# A Mac has its own /etc/pf.conf and /etc/ssh/sshd_config, and copying those
# over the vm23 mirror is a silent overwrite.
unless on_vps?
  warn "sync: refused - run on vm23 as root (doas ruby34 OPENBSD/sync.rb); this machine's /etc is not the box's"
  exit 2
end

mirrored = []
skipped = []
refused = []
SOURCES.each do |repo_rel, live_path|
  unless File.exist?(live_path)
    skipped << live_path
    next
  end
  body = File.read(live_path, encoding: "UTF-8", invalid: :replace, undef: :replace)
  # Refuse before writing: a mirrored file is the drift gate's comparison
  # source, so a secret the patterns never learned would sit in git until
  # someone reads it. A refusal surfaces the line here instead.
  if (left = SecretRedaction.residue(body)).any?
    refused << live_path
    warn "sync: refused #{live_path} - secret-shaped lines survived redaction:"
    left.each { |line| warn "  #{line}" }
    warn "  extend lib/secret_redaction.rb patterns if these are benign"
    next
  end
  dest = File.join(MIRROR, repo_rel)
  FileUtils.mkdir_p(File.dirname(dest))
  File.write(dest, redact(body))
  mirrored << live_path
end

puts "mirrored #{mirrored.size}:"
mirrored.each { |p| puts "  #{p}" }
if skipped.any?
  puts "skipped (not present): #{skipped.size}"
  skipped.each { |p| puts "  #{p}" }
end
exit 3 if refused.any?
