#!/bin/ksh
daemon="/usr/local/bin/bundle"
daemon_flags="exec env RAILS_ENV=production SECRET_KEY_BASE=__REDACTED__ HOME=/home/amber falcon serve --bind http://127.0.0.1:61352"
daemon_user="amber"
daemon_execdir="/home/amber/app"
daemon_timeout="60"
. /etc/rc.d/rc.subr
pexp="ruby.*61352"
rc_bg=YES
rc_reload=NO
rc_cmd $1
