const DB_NAME="pub4-pwa";const DB_VERSION=1;const STORE="mutations";const EVENT="pub4:pwa-queue";const canUseIndexedDB=()=>typeof indexedDB!=="undefined";
const openDb=()=>new Promise((resolve,reject)=>{if(!canUseIndexedDB()){reject(new Error("IndexedDB unavailable"));return}const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:"id"});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const withStore=async(mode,work)=>{const db=await openDb();try{const tx=db.transaction(STORE,mode);const store=tx.objectStore(STORE);const value=await work(store);await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error("transaction aborted"))});return value}finally{db.close()}};
const notify=(type,detail={})=>window.dispatchEvent(new CustomEvent(EVENT,{detail:{type,...detail}}));
const serializeFormData=(formData)=>Array.from(formData.entries()).map(([name,value])=>value instanceof File?{name,kind:"file",blob:value,name_on_disk:value.name,type:value.type,last_modified:value.lastModified}:{name,kind:"text",value:String(value)});
const deserializeFormData=(entries)=>{const formData=new FormData();entries.forEach(entry=>entry.kind==="file"?formData.append(entry.name,entry.blob,entry.name_on_disk):formData.append(entry.name,entry.value));return formData};
export const enqueueForm=async(form)=>{const id=crypto.randomUUID();const formData=new FormData(form);const record={id,created_at:Date.now(),url:new URL(form.action,location.href).toString(),method:(form.method||"POST").toUpperCase(),entries:serializeFormData(formData)};await withStore("readwrite",store=>new Promise((resolve,reject)=>{const request=store.put(record);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)}));notify("queued",{id,count:await queueSize()});return id};
export const queueSize=async()=>withStore("readonly",store=>new Promise((resolve,reject)=>{const request=store.count();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}));
export const replay=async()=>{if(!navigator.onLine||!canUseIndexedDB())return;const records=await withStore("readonly",store=>new Promise((resolve,reject)=>{const request=store.getAll();request.onsuccess=()=>resolve(request.result.sort((a,b)=>a.created_at-b.created_at));request.onerror=()=>reject(request.error)}));
for(const record of records){try{const response=await fetch(record.url,{method:record.method,body:deserializeFormData(record.entries),credentials:"include",redirect:"follow",headers:{"X-Idempotency-Key":record.id,"X-Pub4-Offline-Replay":"1"}});if(response.ok||response.status===409){await withStore("readwrite",store=>new Promise((resolve,reject)=>{const request=store.delete(record.id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)}));notify("replayed",{id:record.id});}else{notify("blocked",{id:record.id,status:response.status});break;}}catch(error){notify("offline",{id:record.id,error:String(error)});break;}}
notify("drained",{count:await queueSize()})};
export const requestStoragePersistence=async()=>navigator.storage?.persist?await navigator.storage.persist():false;
export const installOfflineQueue=()=>{if(window.__pub4OfflineQueueInstalled||!canUseIndexedDB())return;window.__pub4OfflineQueueInstalled=true;requestStoragePersistence().catch(()=>{});window.addEventListener("online",replay);window.addEventListener("pub4:pwa-replay",replay);document.addEventListener("submit",async event=>{const form=event.target;if(!(form instanceof HTMLFormElement)||!form.matches("form[data-pwa-offline]"))return;if(navigator.onLine)return;event.preventDefault();try{await enqueueForm(form);const status=form.querySelector("[data-pwa-queue-status]");if(status)status.textContent=form.dataset.pwaQueuedText||"Lagret for offline";}catch(error){console.error("pub4 offline queue:",error);}});replay().catch(error=>console.warn("pub4 offline queue replay:",error))};
export const pwaCapabilities=()=>({share_target:true,media_session:"mediaSession"in navigator,app_shortcuts:true,launch_handler:"launchQueue"in window,web_share_level_2:"canShare"in navigator,indexeddb:canUseIndexedDB(),opfs:Boolean(navigator.storage?.getDirectory),periodic_background_sync:"serviceWorker"in navigator&&"periodicSync"in ServiceWorkerRegistration.prototype,barcode_detector:"BarcodeDetector"in window,wake_lock:"wakeLock"in navigator,fullscreen:Boolean(document.documentElement.requestFullscreen),geolocation:"geolocation"in navigator,document_picture_in_picture:"documentPictureInPicture"in window});
