# frozen_string_literal: true

require "open3"
require_relative "../../core/paths"

module Master
  module Fix
    class FixLoop
      class FileCollector
        # Exclusion is Scanner's, not ours.
        #
        # This class used to carry its own SKIP_DIRS list, a strict subset of
        # the scanner's, and the gap was not academic: Scanner::SKIP_RELATIVE_PATHS
        # names web/public/three.face.module.js, face.runtime.js and the two
        # face bundles precisely because they are generated or vendored, and
        # /scan honoured that while /fix did not. So `/fix .` proposed 2954
        # violations against a minified THREE build and 931 against a file whose
        # first line reads "Generated by rails assets:build_face_runtime -- do
        # not edit by hand", plus 798 against reports/, which scan skips as
        # generated output. Two lists, one of them wrong, and the wrong one held
        # the write end.
        #
        # A file that must not be edited is not a file worth collecting for a
        # fix pass, so there is one list now and the scanner owns it.
        attr_reader :skipped, :candidate_count, :skip_reasons, :blocking_skips

        def initialize(root:, bus: nil)
          @root = root
          @bus = bus
          @skipped = 0
          @candidate_count = 0
          @skip_reasons = {}
          @blocking_skips = {}
        end

        def collect(target)
          candidates = repository_files(target)
          candidates = Dir.glob(File.join(target, "**", "*")).select { |file| File.file?(file) } if candidates.nil?
          retain(candidates)
        end

        def collect_changed(target)
          changed = changed_since_last_commit(target)
          return collect(target) if changed.empty?

          retain(changed)
        rescue StandardError => e
          @bus&.publish("fix_loop:incremental_error", error: e.message)
          raise "incremental fix scope unavailable: #{e.class}: #{e.message}"
        end

        private

        # Git paths are relative to the repository root, not to the FixLoop root.
        # MASTER is normally @root, but RAILS/OPENBSD/STUDIO targets are not, and
        # treating @root as the Git root quietly made incremental collection fall
        # back to a full directory sweep.
        def repository_files(target)
          root = git_root
          return nil unless root

          out, _, status = Master::Io::Exec.capture3(
            "git", "-C", root, "ls-files", "-z", "--cached", "--others", "--exclude-standard"
          )
          raise "git ls-files failed while collecting #{target}" unless status.success?

          out.split("\0").map { |rel| File.join(root, rel) }
             .select { |file| File.file?(file) && under_path?(file, target) }
        rescue StandardError => e
          Master::Ground::Swallow.log(e, context: "FileCollector.repository_files")
          raise "git inventory unavailable: #{e.class}: #{e.message}"
        end

        def changed_since_last_commit(target)
          root = git_root
          return [] unless root

          tracked, _, tracked_status = Master::Io::Exec.capture3(
            "git", "-C", root, "diff", "--name-only", "HEAD", "--"
          )
          raise "git diff failed while determining incremental fix scope" unless tracked_status.success?

          untracked, _, untracked_status = Master::Io::Exec.capture3(
            "git", "-C", root, "ls-files", "-z", "--others", "--exclude-standard"
          )
          raise "git ls-files failed while determining incremental fix scope" unless untracked_status.success?

          paths = tracked.lines.map(&:strip).reject(&:empty?) + untracked.split("\0").reject(&:empty?)
          paths.uniq.map { |rel| File.join(root, rel) }
               .select { |file| File.file?(file) && under_path?(file, target) }
        end

        def path_policy_root
          git_root || @root
        end

        def git_root
          out, err, status = Master::Io::Exec.capture3("git", "-C", @root, "rev-parse", "--show-toplevel")
          return out.to_s.strip.then { |path| path.empty? ? nil : File.expand_path(path) } if status.success?
          return nil unless checkout_present?

          detail = err.to_s.strip
          raise "git root lookup failed: #{detail.empty? ? "exit #{status.exitstatus}" : detail}"
        end

        def checkout_present?
          current = File.expand_path(@root)
          loop do
            return true if File.exist?(File.join(current, ".git"))

            parent = File.dirname(current)
            return false if parent == current

            current = parent
          end
        end

        # Counted and published rather than quietly dropped — a fix pass that
        # silently narrows its own input reads as "nothing left to do".
        def retain(files)
          @candidate_count = files.size
          @skip_reasons = Hash.new(0)
          @blocking_skips = Hash.new(0)
          kept = []
          dropped = []

          files.each do |file|
            reason = skip_reason(file)
            if reason
              dropped << file
              @skip_reasons[reason.to_s] += 1
              @blocking_skips[reason.to_s] += 1 if %i[too_large too_many_lines].include?(reason)
            else
              kept << file
            end
          end

          @skipped = dropped.size
          if dropped.any?
            @bus&.publish(
              "fix_loop:skipped",
              count: dropped.size,
              reasons: @skip_reasons.sort_by { |reason, count| [-count, reason] }.to_h,
              sample: dropped.first(5).map { |f| relative(f) }
            )
          end
          kept.sort
        end

        def skipped?(path) = !skip_reason(path).nil?

        def skip_reason(path)
          return :scanner_path_filter if Master::Fix::Scanner.skip_path?(path, root: path_policy_root)
          return :symlink if File.symlink?(path)
          return :binary if binary?(path)
          return :too_large if File.size(path) > Master::Fix::Scan::FileProcessor::MAX_FILE_BYTES
          return :too_many_lines if too_many_lines?(path)
          return :immutable if immutable?(path)
          return :rails_history if rails_history?(path)

          nil
        end

        # soul.yml is the constitutional source for sacred paths. The catalogue in
        # laws.yml describes laws; it does not own write protection.
        def immutable?(path)
          policy_root = git_root || @root
          Master::Core::Paths.sacred?(path, root: policy_root)
        end

        # Rails migrations are historical record, not repairable source. They
        # remain visible to migration-safety gates, but /fix must never rewrite
        # them as ordinary violations because changing history does not repair
        # the deployed database.
        def rails_history?(path)
          absolute = File.expand_path(path)
          if (root = git_root)
            relative = absolute.delete_prefix("#{root}#{File::SEPARATOR}")
            return true if relative.match?(%r{\ARAILS/(?:[^/]+/)*db/migrate(?:/|$)})
          end

          local_root = File.expand_path(@root)
          return false unless File.basename(local_root) == "RAILS"

          relative = absolute.delete_prefix("#{local_root}#{File::SEPARATOR}")
          relative.match?(%r{\A(?:[^/]+/)*db/migrate(?:/|$)})
        end

        def relative(path)
          path.to_s.delete_prefix("#{@root}#{File::SEPARATOR}")
        end

        def too_many_lines?(path)
          limit = Master::Fix::Scan::FileProcessor::MAX_LINES
          File.foreach(path, encoding: "UTF-8", invalid: :replace, undef: :replace)
              .with_index(1) { |_, line| return true if line > limit }
          false
        rescue StandardError
          true
        end

        def binary?(path)
          File.file?(path) && Master.binary_file?(path)
        rescue StandardError
          true
        end

        def under_path?(path, root)
          exp = File.expand_path(path)
          exp_root = File.expand_path(root)
          exp == exp_root || exp.start_with?("#{exp_root}#{File::SEPARATOR}")
        end
      end
    end
  end
end
