#!/usr/bin/env ruby
# frozen_string_literal: true

# The seed-media lane: render every photograph the three RAILS apps seed with.
#
#   ruby STUDIO/lora/_toolkit/run_seed_media_colab.rb
#
# Writes STUDIO/lora/seed_media.ipynb. Commit it, open it from the GitHub URL
# this prints, set HF_TOKEN in the sidebar, and run.
#
# A separate generator from run_train_colab.rb rather than a fourth flag on it,
# because that script is subject-scoped — it aborts without SUBJECT and writes
# into SUBJECT_DIR. This set spans three apps and two thirds of it has no subject
# at all, so it belongs beside seed_media.yml and not inside anyone's folder.
#
# The render cell is self-contained diffusers rather than a call into the
# ai-toolkit render path, and that is deliberate. That path composes a prompt
# from the shoots schema — trigger, descriptor, scene, key, distance, lens,
# stock — and prepends the subject to every one. Two of these three populations
# must have no subject in front of them, and all sixty-one must land on an exact
# filename the seeds already look up. Bending the shoots renderer into that shape
# would leave neither job legible.

require "json"
require "yaml"
require "pathname"

LORA_ROOT = Pathname.new(__dir__).join("..").expand_path
SPEC = LORA_ROOT.join("seed_media.yml")
NOTEBOOK = LORA_ROOT.join("seed_media.ipynb")
REPO = ENV.fetch("PUB4_REPO", "anon987654321/pub4")
BRANCH = ENV.fetch("PUB4_BRANCH", "main")

abort "warn: no #{SPEC}" unless SPEC.file?
spec = YAML.safe_load_file(SPEC)
counts = {
  dating: spec.dig("dating", "profiles").size,
  scenes: spec["scenes"].size,
  amber: spec.dig("amber", "garments").size,
}
total = counts.values.sum

def cell(type, source)
  base = { "cell_type" => type, "metadata" => {}, "source" => source.lines }
  type == "code" ? base.merge("execution_count" => nil, "outputs" => []) : base
end

markdown = <<~MARKDOWN
  # Seed media — #{total} photographs for brgen, amber and bsdports

  **Runtime → Change runtime type → T4 GPU** before running.

  Set `HF_TOKEN` in the sidebar (🔑) to a token that has accepted the
  [FLUX.1-dev licence](https://huggingface.co/black-forest-labs/FLUX.1-dev).
  A token without it downloads a 403 that surfaces hundreds of lines later
  inside diffusers, so the setup cell checks for it before anything else.

  Three passes, in this order, because the adapter is loaded once and unloading
  it costs a reload:

  1. **dating** — #{counts[:dating]} frames, Ragnhild's adapter at weight
     #{spec.dig('dating', 'lora_weight')}
  2. **scenes** — #{counts[:scenes]} frames, base model, no adapter
  3. **amber** — #{counts[:amber]} frames, base model, the one mannequin

  Roughly 20–40 s a frame on a T4 at nf4, so about half an hour of GPU plus the
  model download. Output goes to Drive; a disconnect costs the frames since the
  last write and not the session.

  Prompts are `STUDIO/lora/seed_media.yml`. Edits belong there — this notebook is
  generated by `_toolkit/run_seed_media_colab.rb` and is overwritten.
MARKDOWN

token_cell = <<~PYTHON
  import os
  try:
      from google.colab import userdata
      os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")
      print("ok: HF_TOKEN from Colab secrets")
  except Exception:
      import getpass
      os.environ["HF_TOKEN"] = getpass.getpass("HF token (FLUX.1-dev licence accepted): ")
  assert os.environ.get("HF_TOKEN"), "no HF token"

  # Fail here, not four hundred lines into a download. A token that has not
  # accepted the licence gets 403 on the weights and the traceback names a
  # missing file rather than a missing acceptance.
  import urllib.request
  req = urllib.request.Request(
      "https://huggingface.co/api/models/black-forest-labs/FLUX.1-dev",
      headers={"Authorization": f"Bearer {os.environ['HF_TOKEN']}"})
  try:
      urllib.request.urlopen(req).read(1)
      print("ok: FLUX.1-dev reachable with this token")
  except Exception as e:
      raise SystemExit(
          "FLUX.1-dev is not reachable with this token. Accept the licence at "
          "https://huggingface.co/black-forest-labs/FLUX.1-dev and rerun. " + str(e))
PYTHON

drive_cell = <<~PYTHON
  # Frames go to Drive as they are made. A free session disconnects when idle and
  # is capped near 12 h; writing at the end would make every disconnect cost the
  # whole run.
  import os
  from google.colab import drive
  drive.mount("/content/drive")
  OUT = "/content/drive/MyDrive/seed_media"
  os.makedirs(OUT, exist_ok=True)
  print("ok:", OUT)
PYTHON

setup_cell = <<~PYTHON
  import subprocess, os
  # bitsandbytes for nf4, peft for the adapter, sentencepiece for T5's tokenizer.
  subprocess.run(
      "pip -q install -U diffusers transformers accelerate safetensors "
      "bitsandbytes peft sentencepiece protobuf",
      shell=True, check=True)

  if not os.path.isdir("/content/pub4/.git"):
      subprocess.run(
          "git clone --depth 1 --branch #{BRANCH} https://github.com/#{REPO}.git /content/pub4",
          shell=True, check=True)
  print("ok: toolkit and prompts at /content/pub4")

  # Assert the GPU before anything expensive believes it has one.
  #
  # Without this the notebook installs, clones, downloads twenty gigabytes and
  # then renders on the CPU, where a 12B transformer is minutes per step -- so
  # the first sign of a missed Runtime -> T4 is a frame that never arrives.
  # Colab also nags about an idle GPU while these setup cells run, which is
  # correct and means nothing; this is the check that does mean something.
  import torch
  if not torch.cuda.is_available():
      raise SystemExit(
          "no CUDA device. Runtime -> Change runtime type -> T4 GPU, then rerun. "
          "Do not switch to a standard runtime: FLUX.1-dev on CPU is minutes per step.")
  free, total = torch.cuda.mem_get_info()
  print(f"ok: {torch.cuda.get_device_name(0)}, {total / 1e9:.1f} GB total, {free / 1e9:.1f} GB free")
  if total < 14e9:
      print("warn: under 14 GB — nf4 fits a 16 GB T4 with little to spare")
PYTHON

render_cell = <<~PYTHON
  import gc, os, yaml, torch
  from diffusers import FluxPipeline, BitsAndBytesConfig, FluxTransformer2DModel
  from transformers import T5EncoderModel, BitsAndBytesConfig as TfBitsAndBytesConfig

  SPEC = "/content/pub4/STUDIO/lora/seed_media.yml"
  spec = yaml.safe_load(open(SPEC))
  MODEL = "black-forest-labs/FLUX.1-dev"

  # float16, not bfloat16. A T4 is Turing (sm_75) and has no bf16 at all, which is
  # the single fact that decides every dtype below.
  DTYPE = torch.float16

  # Both the transformer and T5 are quantised, and both have to be. nf4 puts the
  # 12B transformer near 6.5 GB, but T5-XXL is another 9 GB in fp16 and 16 GB does
  # not hold both plus activations. Quantised together they fit with room for the
  # VAE decode.
  nf4 = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                           bnb_4bit_compute_dtype=DTYPE)
  tf_nf4 = TfBitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                                bnb_4bit_compute_dtype=DTYPE)

  transformer = FluxTransformer2DModel.from_pretrained(
      MODEL, subfolder="transformer", quantization_config=nf4, torch_dtype=DTYPE)
  text_encoder_2 = T5EncoderModel.from_pretrained(
      MODEL, subfolder="text_encoder_2", quantization_config=tf_nf4, torch_dtype=DTYPE)

  pipe = FluxPipeline.from_pretrained(
      MODEL, transformer=transformer, text_encoder_2=text_encoder_2, torch_dtype=DTYPE)
  # Offload rather than .to("cuda"): it keeps only the active submodule resident,
  # which is what leaves headroom for the VAE at 1024px.
  pipe.enable_model_cpu_offload()
  pipe.set_progress_bar_config(disable=True)
  print("ok: FLUX.1-dev loaded nf4")

  RATIOS = {"3:2": (1216, 832), "4:5": (896, 1120), "1:1": (1024, 1024), "4:3": (1152, 864)}

  def size_for(ratio):
      return RATIOS.get(ratio or spec["meta"]["aspect_ratio"], (1024, 1024))

  def render(key, prompt, ratio, seed):
      path = os.path.join(OUT, key + ".png")
      # Resume is free and a disconnect is not. Re-running skips what landed.
      if os.path.exists(path):
          print("skip", key); return
      w, h = size_for(ratio)
      image = pipe(prompt=prompt, width=w, height=h,
                   guidance_scale=spec["meta"]["guidance"],
                   num_inference_steps=spec["meta"]["steps"],
                   generator=torch.Generator("cpu").manual_seed(seed)).images[0]
      image.save(path)
      print("ok", key, f"{w}x{h}")

  # Pass 1 — dating. The adapter is loaded once for the whole pass and unloaded
  # after, because two thirds of this set must render without it.
  dating = spec["dating"]
  # The adapter is NOT in the clone. STUDIO/lora/*/weights/ is gitignored -- the
  # checkpoints are 218 MB and they are a person's likeness, so the repo is the
  # wrong home for them and Drive is where the training notebook already puts
  # them. Looked for in Drive first, in the same per-subject directory
  # LORA_PERSIST_DIR names, then in the clone in case someone put one there.
  SUBJECT = dating["lora"]
  ADAPTER_CANDIDATES = [
      f"/content/drive/MyDrive/lora/{SUBJECT}/{SUBJECT}.safetensors",
      f"/content/drive/MyDrive/lora/{SUBJECT}/weights/{SUBJECT}.safetensors",
      f"/content/drive/MyDrive/seed_media/{SUBJECT}.safetensors",
      f"/content/pub4/STUDIO/lora/{SUBJECT}/weights/{SUBJECT}/{SUBJECT}.safetensors",
  ]
  # Any checkpoint in the Drive persist dir, newest last, so a run that trained
  # further does not need this list edited.
  import glob
  ADAPTER_CANDIDATES += sorted(glob.glob(f"/content/drive/MyDrive/lora/{SUBJECT}/*.safetensors"))
  ADAPTER = next((p for p in ADAPTER_CANDIDATES if os.path.exists(p)), None)
  if ADAPTER:
      # set_adapters, never fuse_lora. Fusing writes the adapter into the base
      # weights, and these are nf4 -- bitsandbytes 4-bit layers cannot be
      # written back into, so fuse raises partway through the dating pass, on
      # the GPU, after the model has already downloaded. Scaling a named
      # adapter leaves the quantised weights untouched.
      pipe.load_lora_weights(ADAPTER, adapter_name="subject")
      pipe.set_adapters(["subject"], adapter_weights=[dating["lora_weight"]])

      # The trigger comes from subject.env, the file the adapter was trained
      # against. Hardcoding it is how a rename yields twelve pictures of
      # nobody in particular.
      env_path = "/content/pub4/STUDIO/lora/" + dating["lora"] + "/subject.env"
      trigger = dating["lora"]
      if os.path.exists(env_path):
          for line in open(env_path):
              if line.startswith("TRIGGER="):
                  trigger = line.split("=", 1)[1].strip().strip('"').strip("'")
      print("ok: adapter loaded, trigger =", trigger)

      for i, (key, prompt) in enumerate(dating["profiles"].items()):
          render(key, prompt.replace("TRIGGER", trigger), dating["aspect_ratio"], 1000 + i)

      pipe.delete_adapters("subject")
      gc.collect(); torch.cuda.empty_cache()
      print("ok: dating pass complete, adapter unloaded")
  else:
      # Named loudly, and with the fix in it. Rendering these on the base
      # model produces twelve strangers that look like a result and are not.
      print("SKIPPED dating — no adapter found. Looked in:")
      for p in ADAPTER_CANDIDATES:
          print("   ", p)
      print("")
      print(f"  Put {SUBJECT}.safetensors in MyDrive/lora/{SUBJECT}/ and rerun this cell.")
      print("  It is gitignored on purpose, so the clone will never carry it.")
  # Pass 2 — scenes. No adapter, no face where a face is not the subject.
  for i, (key, entry) in enumerate(spec["scenes"].items()):
      render(key, entry["prompt"], entry.get("aspect_ratio"), 2000 + i)

  # Pass 3 — amber. The mannequin clause is prepended rather than repeated in
  # each entry, so seventeen garments share one mannequin instead of seventeen
  # subtly different ones.
  amber = spec["amber"]
  for i, (key, garment) in enumerate(amber["garments"].items()):
      render(key, spec["mannequin"] + ", " + garment, amber["aspect_ratio"], 3000 + i)

  made = len([f for f in os.listdir(OUT) if f.endswith(".png")])
  print(f"\\nok: {made} frame(s) in {OUT}")
  print("next: download that folder, then on the Mac:")
  print("  ruby STUDIO/lora/_toolkit/install_seed_media.rb <folder>")
PYTHON

notebook = {
  "cells" => [
    cell("markdown", markdown),
    cell("code", token_cell),
    cell("code", drive_cell),
    cell("code", setup_cell),
    cell("code", render_cell),
  ],
  "metadata" => {
    "accelerator" => "GPU",
    "colab" => { "provenance" => [], "gpuType" => "T4" },
    "kernelspec" => { "display_name" => "Python 3", "name" => "python3" },
    "language_info" => { "name" => "python" },
  },
  "nbformat" => 4,
  "nbformat_minor" => 0,
}

NOTEBOOK.write("#{JSON.pretty_generate(notebook)}\n")
puts "ok: wrote #{NOTEBOOK.relative_path_from(LORA_ROOT.parent.parent)}"
puts "ok: #{total} frames — #{counts[:dating]} dating, #{counts[:scenes]} scenes, #{counts[:amber]} amber"
puts
puts "next: commit and push, then open"
puts "  https://colab.research.google.com/github/#{REPO}/blob/#{BRANCH}/STUDIO/lora/seed_media.ipynb"
