# frozen_string_literal: true

require "minitest/autorun"
require_relative "../shared/lib/pub4/fallback_drift_lint"

# The second half of the lint: a token declared nowhere at all.
#
# The first half compared a hex fallback against known values and skipped the
# case where no value was known -- its own line said so, and that skip hid
# thirteen dead indirections. var(--card-min-width, 280px) was 280px wearing a
# token's clothes; .tv-feed-title asked for var(--text-md) with no fallback and
# shipped with no font-size at all.
#
# The instrument is the risk here, not the finding. Two shapes look undeclared
# and are not: a name generated by SCSS interpolation, and a name a helper or
# JS writes at runtime. Both were false positives before these cases pinned
# them -- --vertical-dating-accent is emitted seven times over by
# _vertical_shell.scss, and --nick-hue is written into a style attribute by
# ChatHelper.
class FallbackDriftLintTest < Minitest::Test
  LINT = Pub4::FallbackDriftLint

  def test_the_tree_declares_every_token_it_asks_for
    undeclared = LINT.undeclared_uses.map do |v|
      "#{v.file}:#{v.line} #{v.token} (#{v.fallback_hex || 'no fallback'})"
    end

    assert_empty undeclared, "var() names nothing declares"
  end

  def test_an_interpolated_declaration_covers_the_family_it_emits
    _names, families = LINT.declared_names

    refute_empty families, "no interpolated declaration found; this test would prove nothing"
    assert families.any? { |f| f.match?("--vertical-dating-accent") },
           "_vertical_shell.scss emits --vertical-<v>-accent; the check must not call it undeclared"
  end

  def test_a_name_written_at_runtime_counts_as_declared
    names, _families = LINT.declared_names

    assert_includes names, "--nick-hue", "ChatHelper writes --nick-hue into a style attribute"
    assert_includes names, "--read-more-line-clamp", "the read-more component sets it with setProperty"
  end
end
