# frozen_string_literal: true

require "minitest/autorun"
require "tmpdir"

# rb_file_too_long / scss_file_too_long / view_too_long, as a ratchet rather than
# three lists — the same conclusion method_length_ratchet_test.rb reaches, for the
# same reason: a finding list is a snapshot and cannot hold a line while you work
# down it.
#
# Counted in code lines, non-blank and non-comment, matching lint:spine (which was
# re-expressed the same day), [DENSITY], and the method ratchet. Under the raw
# count these rules charged for documentation, and this tree's convention is a
# paragraph of rationale above the tricky line. Four of the recorded 24 findings
# were only ever over the limit on their comments: _brand.scss (441 raw / 379
# code), _chrome_polish.scss (405/366), amber's application layout (153/143) and
# gates/lib/page_simulation.rb (360/295).
#
# Generated files are excluded rather than exempted-in-place, because "split it"
# is not an available action for them: db/schema.rb is written by Rails from the
# migrations and hand-edits are overwritten on the next `db:migrate`. brgen's is
# 1,359 code lines and will never be anything else.
class FileLengthRatchetTest < Minitest::Test
  ROOT = File.expand_path("..", __dir__)

  # kind => [glob roots, limit in code lines]
  LIMITS = { "rb" => 300, "scss" => 400, "erb" => 150 }.freeze

  # Rails writes these from the migrations; a split is undone by the next
  # db:migrate. Excluded, not allow-listed, so they never read as debt.
  GENERATED = %r{/db/schema\.rb\z}

  # file => code lines. Measured 2026-08-10. Lower a number when you split
  # something; never raise one, and never add a row without saying why here.
  #
  # db/seeds.rb and plausible_content.rb are data rather than logic — long lists
  # of seed rows and sample copy. They are on the list because splitting them is
  # possible, not because it is obviously worth doing.
  CEILINGS = {
    "brgen/lib/brgen/bergen_demo_seeder.rb" => 839,
    "brgen/test/services/deploy_backlog_test.rb" => 756,
    "gates/lib/design_metrics.rb" => 522,
    "gates/lib/geometry.rb" => 498,
    "gates/support/page_inventory.rb" => 434,
    "gates/support/cdp_session.rb" => 428,
    "brgen/app/services/tradedoubler.rb" => 426,
    "brgen/db/seeds.rb" => 421,
    "gates/support/geometry_probe.rb" => 410,
    "brgen/lib/brgen/plausible_content.rb" => 344,
    "amber/app/services/wardrobe_ai.rb" => 319,
    "gates/lib/user_flow.rb" => 314,
    "shared/app/assets/stylesheets/_minimal.scss" => 514,
    "shared/app/assets/stylesheets/_shell.scss" => 507,
    "shared/app/assets/stylesheets/_zen_shell.scss" => 491,
    "shared/app/assets/stylesheets/_shell_widgets.scss" => 489,
    "bsdports/app/assets/stylesheets/application.scss" => 454,
    "brgen/app/views/layouts/application.html.erb" => 304,
    "brgen/engines/playlist/app/views/playlist/playlists/_player.html.erb" => 160,
    "brgen/app/views/pwa/manifest.json.erb" => 152,
  }.freeze

  COMMENT_STARTS = ["#", "//", "/*", "*", "<%#"].freeze

  def code_lines(path)
    File.readlines(path).count do |line|
      stripped = line.strip
      !stripped.empty? && !stripped.start_with?(*COMMENT_STARTS)
    end
  end

  def candidates
    @candidates ||= begin
      apps = %w[shared brgen amber bsdports gates tools test lib]
      rb = apps.flat_map { |a| Dir.glob(File.join(ROOT, a, "**/*.rb")) }
      scss = %w[shared brgen amber bsdports].flat_map { |a| Dir.glob(File.join(ROOT, a, "**/*.scss")) }
      erb = %w[shared brgen amber bsdports].flat_map do |a|
        Dir.glob(File.join(ROOT, a, "app/views/**/*.erb")) +
          Dir.glob(File.join(ROOT, a, "engines/*/app/views/**/*.erb"))
      end
      { "rb" => rb, "scss" => scss, "erb" => erb }.transform_values do |paths|
        paths.reject { |p| p.match?(%r{/(vendor|node_modules|public)/|/db/migrate/}) || p.match?(GENERATED) }
             .uniq.sort
      end
    end
  end

  def oversize
    candidates.flat_map do |kind, paths|
      limit = LIMITS.fetch(kind)
      paths.filter_map do |path|
        lines = code_lines(path)
        [path.delete_prefix("#{ROOT}/"), lines] if lines > limit
      end
    end.to_h
  end

  def test_the_scan_reaches_the_tree_it_claims_to
    assert candidates.values.all? { |paths| paths.size.positive? }, "a glob returned nothing"
    assert candidates["erb"].any? { |p| p.include?("/engines/") },
           "engine views are missing, the blind spot that hid 57 of them"
  end

  def test_generated_schema_is_excluded_not_counted
    schema = File.join(ROOT, "brgen/db/schema.rb")
    skip "brgen/db/schema.rb absent" unless File.exist?(schema)

    assert_operator code_lines(schema), :>, LIMITS["rb"],
                    "if schema.rb were short this exclusion would be pointless"
    refute_includes candidates["rb"], schema,
                    "schema.rb is regenerated by db:migrate — a split is undone, so it is excluded"
  end

  def test_length_is_measured_in_code_lines_not_raw
    Dir.mktmpdir do |dir|
      path = File.join(dir, "documented.rb")
      File.write(path, (["# explanation"] * 500 + ["x = 1"] * 3).join("\n"))
      assert_equal 3, code_lines(path), "500 comment lines must not count against a 3-line file"
    end
  end

  def test_no_file_exceeds_its_ceiling
    risen = oversize.filter_map do |path, lines|
      ceiling = CEILINGS[path]
      if ceiling.nil?
        "#{path}: #{lines} code lines, over the limit and no ceiling declared"
      elsif lines > ceiling
        "#{path}: #{lines} code lines, ceiling is #{ceiling} (+#{lines - ceiling})"
      end
    end

    assert_empty risen, <<~MSG.strip
      files have grown past their ceilings:

        #{risen.join("\n  ")}

      Split the file rather than raising the number. A new entry here means a new
      long file was added, which is the thing three separate measurements of this
      backlog failed to prevent.
    MSG
  end

  def test_ceilings_are_not_slack
    current = oversize
    slack = CEILINGS.filter_map do |path, ceiling|
      next if current[path] == ceiling

      if current[path].nil?
        "#{path}: no longer over the limit — remove the row"
      else
        "#{path}: now #{current[path]}, recorded #{ceiling} — lower it"
      end
    end

    assert_empty slack, <<~MSG.strip
      the tree is better than the ratchet records:

        #{slack.join("\n  ")}

      A ceiling above the real number is slack the next long file grows into
      without failing anything.
    MSG
  end
end
