#!/usr/bin/env ruby
# encoding: utf-8
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
$stdout.set_encoding("UTF-8")
$stderr.set_encoding("UTF-8")

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "master3"

cli = nil

trap("INT")  { cli&.container&.dig(:session)&.save! rescue nil; $stderr.puts "\nsaved"; exit 0 }
trap("TERM") { cli&.container&.dig(:session)&.save! rescue nil; exit 0 }

if $stdin.tty?
  cli     = Master3.boot(root: Dir.pwd, argv: ARGV)
  message = ARGV.join(" ").strip
  cli.run(message.empty? ? nil : message)
else
  cli = Master3.boot(root: Dir.pwd)
  cli.pipe($stdin.read)
end
