source "https://rubygems.org"
ruby ">= 3.4"

gem "rails", "~> 8.1.2"
gem "propshaft"

gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]
gem "falcon"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end

group :test do
  gem "minitest", "~> 5.25"
  gem "puma"
end

group :development do
  gem "web-console"
end