#!/bin/sh
# Generated by MASTER CLI
# Pre-commit hook for fast code quality checks

# Get staged Ruby files
changed_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rb$')

if [ -z "$changed_files" ]; then
  exit 0
fi

echo "MASTER: Analyzing staged files..."

# Run MASTER analysis on staged files (quick profile with cache)
%{master_cli_path} analyze --staged --profile quick --cache --format compact

exit $?
