# Reek configuration for MASTER
detectors:
  IrresponsibleModule:
    enabled: false

  UncommunicativeVariableName:
    accept:
      - a
      - b
      - c
      - d
      - e
      - f
      - g
      - h
      - i
      - j
      - k
      - l
      - m
      - n
      - o
      - p
      - q
      - r
      - s
      - t
      - u
      - v
      - w
      - x
      - y
      - z
      - t0
      - t1
      - id

  UncommunicativeParameterName:
    accept:
      - _
      - _e
      - _k
      - _v

  TooManyStatements:
    max_statements: 20

  TooManyMethods:
    max_methods: 25

  TooManyInstanceVariables:
    max_instance_variables: 10

  TooManyConstants:
    max_constants: 12

  LongParameterList:
    max_params: 6

  UtilityFunction:
    enabled: false

  ManualDispatch:
    enabled: false

  MissingSafeMethod:
    enabled: false

  FeatureEnvy:
    enabled: false

  BooleanParameter:
    enabled: false

  NestedIterators:
    max_allowed_nesting: 2
