# frozen_string_literal: true

require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Routes carry the same host. action_mailer.default_url_options only reaches
  # ActionMailer; anything generating a URL through Rails.application.routes —
  # an isolated engine's main_app proxy, a job, a runner — reads this one, and
  # it was unset in every environment.
  config.after_initialize { Rails.application.routes.default_url_options = { host: "localhost", port: 3000 } }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Debug suits a developer reading the newest few hundred lines at a console.
  # It does not suit a server left up for days answering gate probes: Rails 8.1
  # ships two debug-level view subscribers, the classic LogSubscriber and the
  # structured one, so every partial render costs two lines in a file nothing
  # rotates. A long-lived caller says which it is; bin/triangle is one.
  config.log_level = ENV.fetch("RAILS_LOG_LEVEL", "debug").to_sym

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  # config.assets.quiet = true  # sprockets only — not used with propshaft

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  config.active_record.strict_loading_by_default = true
  config.active_record.action_on_strict_loading_violation = :log

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Every city, not just Bergen.
  #
  # This listed brgen.no, its seven verticals and bsdports.org by hand, so the
  # other 42 apexes in DomainRegistry::ENTRIES answered 403 Blocked Host on a
  # developer's own machine. A network whose entire argument is that each city
  # is its own place could not show you a second one locally — the per-city
  # seed data was unviewable by the person who wrote it.
  #
  # Read from the registry rather than restated. The registry is already the
  # source for routing, for DNS, for acme and for the gates' host lists, and a
  # hand-kept copy beside it drifts the day a city is added: markedsplass is
  # spelled per-country (marknadsplats, marktplatz), so even the vertical list
  # above was only ever right for Norway.
  #
  # Development only. Production takes its hosts from relayd and the certificate
  # on disk, which is a stricter question than "is this one of ours".
  Brgen::DomainRegistry::ENTRIES.each do |entry|
    config.hosts << entry.domain
    config.hosts << /\A([a-z0-9-]+\.)*#{Regexp.escape(entry.domain)}\z/i
  end
  config.hosts << /\A([a-z0-9-]+\.)*localhost\z/i
  # bsdports runs its own apex and is not a city, so no registry entry covers
  # it: probing the local server with its real Host header returned 403.
  config.hosts << "bsdports.org"
  config.hosts << /\A([a-z0-9-]+\.)*bsdports\.org\z/i
end
