permit nopass keepenv dev as root
permit nopass dev as root cmd /sbin/rcctl args restart master
permit nopass dev as root cmd /home/dev/pub4/MASTER/tools/postpro.rb
permit nopass dev as root cmd /home/dev/pub4/MASTER/tools/repligen.rb
