log connection errors
interval 120
timeout 2000

table <brgen> { 127.0.0.1 }
table <amber> { 127.0.0.1 }
table <master> { 127.0.0.1 }
table <bsdports> { 127.0.0.1 }
table <baibl> { 127.0.0.1 }
table <blognet> { 127.0.0.1 }
table <hjerterom> { 127.0.0.1 }

http protocol "https_proxy" {
  tls keypair "brgen.no"
  tls keypair "ai.brgen.no"
  tls keypair "amber.brgen.no"
  tls keypair "baibl.brgen.no"
  tls keypair "blognet.brgen.no"
  tls keypair "bsdports.org"
  match request header set "X-Forwarded-Proto" value "https"
  match request header set "X-Forwarded-For" value "$REMOTE_ADDR"
  match response header set "Strict-Transport-Security" value "max-age=31536000; includeSubDomains; preload"
  match response header set "Referrer-Policy" value "strict-origin"
  match response header set "X-Content-Type-Options" value "nosniff"
  match response header set "X-Frame-Options" value "SAMEORIGIN"
  match response header set "X-XSS-Protection" value "0"
  match response header set "Permissions-Policy" value "accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()"
  match response header remove "Server"
  http websockets
  match request header "Host" value "brgen.no" forward to <brgen>
  match request header "Host" value "www.brgen.no" forward to <brgen>
  match request header "Host" value "tv.brgen.no" forward to <brgen>
  match request header "Host" value "dating.brgen.no" forward to <brgen>
  match request header "Host" value "playlist.brgen.no" forward to <brgen>
  match request header "Host" value "takeaway.brgen.no" forward to <brgen>
  match request header "Host" value "markedsplass.brgen.no" forward to <brgen>
  match request header "Host" value "maps.brgen.no" forward to <brgen>
  match request header "Host" value "messenger.brgen.no" forward to <brgen>
  match request header "Host" value "amber.brgen.no" forward to <amber>
  match request header "Host" value "ai.brgen.no" forward to <master>
  match request header "Host" value "bsdports.org" forward to <bsdports>
  match request header "Host" value "baibl.brgen.no" forward to <baibl>
  match request header "Host" value "blognet.brgen.no" forward to <blognet>
  match request header "Host" value "baibl.no" forward to <baibl>
  match request header "Host" value "blognet.no" forward to <blognet>
  match request header "Host" value "www.blognet.no" forward to <blognet>
  match request header "Host" value "hjerterom.brgen.no" forward to <hjerterom>
  match request header "Host" value "hjerterom.no" forward to <hjerterom>
  pass
}

relay "https_in" {
  listen on 0.0.0.0 port 443 tls
  protocol "https_proxy"
  forward to <brgen> port 38182 check http "/up" code 200
  forward to <amber> port 61352 check http "/up" code 200
  forward to <master> port 53187 check http "/up" code 200
  forward to <bsdports> port 47312 check http "/up" code 200
  forward to <baibl> port 10007 check http "/up" code 200
  forward to <blognet> port 10002 check http "/up" code 200
  forward to <hjerterom> port 38891 check http "/up" code 200
}