#!/bin/ksh
daemon="/usr/local/bin/bundle"
daemon_flags="exec env RAILS_ENV=production SECRET_KEY_BASE= HOME=/home/blognet falcon serve --bind http://127.0.0.1:10002"
daemon_user="blognet"
daemon_execdir="/home/blognet/app"
daemon_timeout="60"
. /etc/rc.d/rc.subr
pexp="ruby.*10002"
rc_bg=YES
rc_reload=NO
rc_cmd $1
