#!/bin/ksh

daemon="/usr/local/bin/ruby34"
daemon_flags="/home/blognet/app/config/falcon.rb"
daemon_user="blognet"
daemon_timeout=30

. /etc/rc.d/rc.subr

pexp="ruby34 /home/blognet/app/config/falcon.rb"
rc_bg=YES
rc_reload=NO

rc_cmd $1
