#!/bin/ksh
daemon="/usr/local/bin/bundle"
daemon_flags="exec env RAILS_ENV=production SECRET_KEY_BASE=__REDACTED__ HOME=/home/brgen_tv falcon serve --bind http://127.0.0.1:10012"
daemon_user="brgen_tv"
daemon_execdir="/home/brgen_tv/app"
daemon_timeout="60"
. /etc/rc.d/rc.subr
pexp="ruby.*10012"
rc_bg=YES
rc_reload=NO
rc_cmd $1
