#!/bin/ksh
daemon="/usr/local/bin/bundle"
daemon_flags="exec env RAILS_ENV=production SECRET_KEY_BASE= HOME=/home/bsdports falcon serve --bind http://127.0.0.1:47312"
daemon_user="bsdports"
daemon_execdir="/home/bsdports/app"
daemon_timeout="60"
. /etc/rc.d/rc.subr
pexp="ruby.*47312"
rc_bg=YES
rc_reload=NO
rc_cmd $1
