#!/bin/sh
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
. "$ROOT/script/bundle_size.sh"
PUB="$ROOT/public"
OUT="$PUB/face_vision.bundle.js"
SOURCE_DIGEST="$(ruby -rdigest -e 'puts Digest::SHA256.hexdigest(ARGV.sort.map { |p| File.binread(p) }.join("\0"))' \
  "$PUB/face_vision_core.js" "$PUB/face_vision_a.js" "$PUB/face_vision_b.js" "$PUB/face_vision_c.js" "$PUB/face_vision_d.js")"
{
  echo "// Generated by script/build_face_vision.sh — do not edit by hand."
  echo "// SOURCE-SET-SHA256: $SOURCE_DIGEST"
  for part in face_vision_core.js face_vision_a.js face_vision_b.js face_vision_c.js face_vision_d.js; do
    path="$PUB/$part"
    test -f "$path" || { echo "missing $path" >&2; exit 1; }
    cat "$path"
    echo ""
  done
} > "$OUT"
report_bundle_size "$OUT"
