# PF for DNS, HTTP/HTTPS, SSH, SMTP (pf.conf(5))
ext_if="vio0"
brgen_ip="$BRGEN_IP"
hyp_ip="$HYP_IP"
set skip on lo
set block-policy return
set loginterface \$ext_if
set reassemble yes
set limit { states 10000, frags 5000 }
block log all
scrub in all
table <bruteforce> persist
block quick from <bruteforce>
pass out quick on \$ext_if all
pass in on \$ext_if inet proto tcp to \$ext_if port 22 keep state \\
  (max-src-conn 15, max-src-conn-rate 5/3, overload <bruteforce> flush global)
pass in on \$ext_if inet proto { tcp, udp } to \$brgen_ip port 53 log
pass in on \$ext_if inet proto tcp to \$brgen_ip port { 22, 25, 80, 443, 3000, 8080, 8082, 8084, 8086 } log
pass out on \$ext_if inet proto tcp to any port 25
