import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
const viewsDir = join(root, "app", "views");

function partSources() {
  return [1, 2, 3, 4, 5].map((part) => readFileSync(join(publicDir, `face.part${part}.txt`), "utf8"));
}

test("face.js loads modules and runtime parts through MASTER_ASSET_PATHS", () => {
  const faceJs = readFileSync(join(publicDir, "face.js"), "utf8");
  const tail = readFileSync(join(publicDir, "face.part5.txt"), "utf8");
  assert.match(faceJs, /MASTER_ASSET_PATHS\?\.faceModules\?\.\[modulePath\]/);
  assert.match(faceJs, /MASTER_ASSET_PATHS\?\.faceModulesList/);
  assert.match(faceJs, /MASTER_ASSET_PATHS\?\.faceParts/);
  assert.match(faceJs, /FACE_BLOB_URL/);
  assert.match(tail, /function sendMessage/);
  assert.match(tail, /window\.MASTER_FACE =/);
});

test("face.js builds a blob runtime and rewrites module asset paths", () => {
  const faceJs = readFileSync(join(publicDir, "face.js"), "utf8");
  assert.match(faceJs, /Object\.entries\(MODULE_PATHS\)\.reduce/);
  assert.match(faceJs, /replaceAll/);
  assert.match(faceJs, /URL\.createObjectURL/);
  assert.match(faceJs, /URL\.revokeObjectURL/);
  assert.match(faceJs, /await import\(FACE_BLOB_URL\)/);
});

test("concatenated face parts form a syntactically valid module (guards tap-to-start)", () => {
  // face.js fetches face.part1..5, joins them with "\n", and import()s the blob. A
  // duplicate top-level const (or any syntax error) spanning two parts throws at import
  // time, so window.MASTER_FACE never loads and the primer tap silently does nothing.
  // The per-file assertions above cannot see cross-part collisions — only the join can.
  const blob = partSources().join("\n");
  const tmp = join(tmpdir(), `master-face-blob-${process.pid}.mjs`);
  writeFileSync(tmp, blob);
  try {
    execFileSync(process.execPath, ["--check", tmp], { stdio: "pipe" });
  } catch (err) {
    const detail = err.stderr ? err.stderr.toString() : err.message;
    throw new Error(`concatenated face blob failed syntax check:\n${detail}`);
  } finally {
    rmSync(tmp, { force: true });
  }
});

test("face.modules.bundle.js is generated from face module entry", () => {
  const bundlePath = join(publicDir, "face.modules.bundle.js");
  assert.ok(existsSync(bundlePath), "run rails assets:build_face_modules_bundle");
  const bundle = readFileSync(bundlePath, "utf8");
  assert.match(bundle, /MASTER_FACE_PARTICLES|face_particles/);
  assert.match(bundle, /MASTER_FACE_BLEND|face_blendshape/);
});

test("face.runtime.js is generated from face parts", () => {
  const runtimePath = join(publicDir, "face.runtime.js");
  assert.ok(existsSync(runtimePath), "run rails assets:build_face_runtime");
  const runtime = readFileSync(runtimePath, "utf8");
  const part1 = readFileSync(join(publicDir, "face.part1.txt"), "utf8").trim();
  assert.match(runtime, /Generated by/);
  assert.ok(runtime.includes(part1.slice(0, 120)), "runtime should include part1 body");
});

test("chat index inline boot lazy-imports face with status hint, auto-retry, 35s watchdog", () => {
  const index = readFileSync(join(viewsDir, "chat", "index.html.erb"), "utf8");
  assert.match(index, /MASTER_ASSET_PATHS/);
  assert.match(index, /function loadFace/);
  assert.match(index, /import\("<%= asset_path\("face\.js"\) %>"\)/);
  assert.match(index, /dismissPrimer\(\);\n\s+revealPrompt\(\);/);
  assert.match(index, /error-live/);
  // NN/g recovery + visibility-of-status UX
  assert.match(index, /still loading the face/);
  assert.match(index, /retrying/);
  assert.match(index, /loadFace\(true\)/);
  assert.match(index, /35000/);
  assert.doesNotMatch(index, /60000/);
  assert.doesNotMatch(index, /15000/);
  assert.doesNotMatch(index, /render "shared\/face_boot"/);
});

test("probe_chat_e2e script covers primer chat and felt state", () => {
  const probe = readFileSync(join(root, "script", "probe_chat_e2e.rb"), "utf8");
  const gemfile = readFileSync(join(root, "Gemfile"), "utf8");
  assert.match(probe, /probe_chat_e2e/);
  assert.match(probe, /run_ping_chat/);
  assert.match(probe, /MASTERFeltState/);
  assert.match(probe, /hasPong/);
  assert.match(probe, /MASTER_FACE\?\.State/);
  assert.match(gemfile, /gem "ferrum"/);
  assert.match(probe, /MAX_PROBE_SECONDS/);
  assert.match(probe, /browser\.go_to\(URL\)/);
});

test("probe_webgl_guard covers before-tap canvas lock and after-tap unlock", () => {
  const probe = readFileSync(join(root, "script", "probe_webgl_guard.mjs"), "utf8");
  const ciProbe = readFileSync(join(root, "script", "ci_web_probe"), "utf8");
  assert.match(probe, /HTMLCanvasElement/);
  assert.match(probe, /getContext/);
  assert.match(probe, /WebGL escaped guard before tap/);
  assert.match(probe, /WebGL unavailable after tap/);
  assert.match(probe, /PROBE_REQUIRE_BROWSER/);
  assert.match(ciProbe, /probe_webgl_guard\.mjs/);
});

test("chat index wires digested assets around lazy face boot", () => {
  const index = readFileSync(join(viewsDir, "chat", "index.html.erb"), "utf8");
  assert.match(index, /asset_path\("face\.css"\)/);
  assert.match(index, /asset_path\("face\.js"\)/);
  assert.match(index, /asset_path\("particle_kernel\.js"\)/);
  // Deferred modules now come from one ordered javascript_include_tag manifest, not 9 literal tags.
  assert.match(index, /javascript_include_tag\(\*%w\[[^\]]*chat_actions[^\]]*\]/);
  assert.match(index, /%w\[[^\]]*visual_bridge[^\]]*\]/);
  assert.match(index, /defer: true/);
  assert.doesNotMatch(index, /rel="modulepreload"[^>]+asset_path\("face\.js"\)/);
  assert.match(index, /<link rel="prefetch" href="<%= asset_path\("face\.js"\) %>" as="script">/);
  const particleIdx = index.indexOf('asset_path("particle_kernel.js")');
  const primerIdx = index.indexOf('id="primer"');
  const bootIdx = index.indexOf("function go()");
  assert.ok(primerIdx > 0 && particleIdx > primerIdx, "particle kernel should load after shell markup");
  assert.ok(bootIdx > particleIdx, "inline boot should follow particle kernel script");
});

test("face3d preview consumes TTS events and reports nonblank frames", () => {
  const preview = readFileSync(join(publicDir, "face3d_preview.js"), "utf8");
  const renderer = readFileSync(join(publicDir, "face3d_renderer.js"), "utf8");
  assert.match(preview, /FACE3D_ACTIVE/);
  assert.match(preview, /function bootFace3d/);
  assert.match(preview, /addEventListener\("tts:playback:start"/);
  assert.match(preview, /addEventListener\("tts:viseme"/);
  assert.match(preview, /face3d:nonblank/);
  assert.match(renderer, /lastLitPixels/);
});

test("face.css keeps primer and prompt layering stable", () => {
  const css = readFileSync(join(publicDir, "face.css"), "utf8");
  assert.match(css, /#primer/);
  assert.match(css, /z-index:\s*var\(--z-modal\)/);
  assert.match(css, /body:not\(\.face-ready\) #zsh:not\(\.live\)/);
  assert.match(css, /--x-text:\s*#e7e9ea/);
  assert.match(css, /JetBrainsMono Nerd Font/);
});

test("face3d_engine imports use import-map paths", () => {
  const engine = readFileSync(join(publicDir, "face3d_engine.js"), "utf8");
  assert.match(engine, /from '\/face3d_geometry\.js'/);
  assert.match(engine, /from '\/face3d_support\.js'/);
});

test("visual_bridge connects SSE and normalizes visual events", () => {
  const bridge = readFileSync(join(publicDir, "visual_bridge.js"), "utf8");
  assert.match(bridge, /new EventSource\("\/events\/stream"\)/);
  assert.match(bridge, /MASTERTopology\.classifyEvent/);
  assert.match(bridge, /master:visual/);
  assert.match(bridge, /disconnectSse/);
});

test("ecology render starts RAF and resumes on visual events", () => {
  const ecology = readFileSync(join(publicDir, "cognition_ecology_render.js"), "utf8");
  assert.match(ecology, /ensureEcologyFrame/);
  assert.match(ecology, /addEventListener\("master:visual"/);
  assert.match(ecology, /ecologyFrameActive = false/);
});

test("topology registry exposes canonical classifier", () => {
  const registry = readFileSync(join(publicDir, "topology_registry.js"), "utf8");
  assert.match(registry, /phantom:detected/);
  assert.match(registry, /classifyEvent/);
  assert.match(registry, /bootRemoteTopologies\(\)/);
});

test("chat_actions posts chat stream instead of EventSource GET", () => {
  const actions = readFileSync(join(publicDir, "chat_actions.js"), "utf8");
  assert.match(actions, /method:\s*"POST"/);
  assert.match(actions, /\/chat\/message/);
  assert.doesNotMatch(actions, /new EventSource\(/);
  assert.match(actions, /window\.MASTERChat/);
  assert.match(actions, /MASTER_FACE\?\.sendMessage/);
});

test("face runtime keeps chat stream and particle worker boot paths", () => {
  const runtime = readFileSync(join(publicDir, "face.runtime.js"), "utf8");
  assert.match(runtime, /function sendMessage/);
  assert.match(runtime, /const url = `\/chat\/message\?message=/);
  assert.match(runtime, /evtSrc = new EventSource\(url\)/);
  assert.match(runtime, /new Worker\('\/particle_worker\.js'\)|new Worker\("\/particle_worker\.js"\)/);
  assert.match(runtime, /window\.MASTER_FACE/);
});

test("service worker avoids stale undigested precache", () => {
  const sw = readFileSync(join(publicDir, "sw.js"), "utf8");
  assert.doesNotMatch(sw, /\/face\.js'/);
  assert.doesNotMatch(sw, /\/chat\.js'/);
  assert.match(sw, /OFFLINE_URL/);
  assert.match(sw, /Never cache digested/);
  assert.match(sw, /pathname\.startsWith\('\/assets\/'\)/);
});
