import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
const viewsDir = join(root, "app", "views");

function partSources() {
  return [1, 2, 3, 4, 5].map((part) => readFileSync(join(publicDir, `face.part${part}.txt`), "utf8"));
}

test("face.part tail imports are single-quoted for MODULE_PATHS replacement", () => {
  const tail = partSources().join("\n");
  const imports = [...tail.matchAll(/import\(['"]([^'"]+)['"]\)/g)].map((m) => m[1]);
  const rootImports = imports.filter((path) => path.startsWith("/"));
  assert.deepEqual(rootImports, [
    "/face_semantics.js",
    "/face_minimal_ui.js",
    "/face_loops_music.js",
    "/face_loops_nudge.js"
  ]);
});

test("face.js loader replaces every tail import path", () => {
  const source = partSources().join("\n");
  const faceModules = Object.fromEntries(
    readdirSync(join(publicDir, "assets"))
      .filter((name) => name.endsWith(".js") && name.startsWith("face_"))
      .map((name) => [name.replace(/-[0-9a-f]{8}\.js$/, ".js"), `/assets/${name}`])
  );
  const replaced = Object.entries(faceModules).reduce(
    (out, [name, path]) => out.replaceAll(`'/${name}'`, JSON.stringify(`https://example.test${path}`)),
    source
  );
  assert.doesNotMatch(replaced, /import\('\/face_/);
});

test("face.js dispatches boot stage events and prefers faceRuntime bundle", () => {
  const faceJs = readFileSync(join(publicDir, "face.js"), "utf8");
  assert.match(faceJs, /master:face-stage/);
  assert.match(faceJs, /dispatchFaceStage\("modules"\)/);
  assert.match(faceJs, /dispatchFaceStage\("ready"\)/);
  assert.match(faceJs, /faceRuntime/);
  assert.match(faceJs, /importFaceBlob/);
});

test("face.runtime.js is generated from face parts", () => {
  const runtimePath = join(publicDir, "face.runtime.js");
  assert.ok(existsSync(runtimePath), "run rails assets:build_face_runtime");
  const runtime = readFileSync(runtimePath, "utf8");
  const part1 = readFileSync(join(publicDir, "face.part1.txt"), "utf8").trim();
  assert.match(runtime, /Generated by/);
  assert.ok(runtime.includes(part1.slice(0, 120)), "runtime should include part1 body");
});

test("shared boot partial uses 60s watchdog and error-live", () => {
  const boot = readFileSync(join(viewsDir, "shared", "_face_boot.html.erb"), "utf8");
  assert.match(boot, /60000/);
  assert.match(boot, /error-live/);
  assert.match(boot, /master:face-stage/);
  assert.doesNotMatch(boot, /15000/);
});

test("chat index ships import map and digested master_events", () => {
  const index = readFileSync(join(viewsDir, "chat", "index.html.erb"), "utf8");
  const helper = readFileSync(join(root, "app", "helpers", "face_assets_helper.rb"), "utf8");
  assert.match(index, /type="importmap"/);
  assert.match(index, /master_face_import_map/);
  assert.match(index, /asset_path\("master_events\.js"\)/);
  assert.match(index, /modulepreload/);
  assert.match(helper, /face3d_geometry\.js/);
});

test("face3d_engine imports use import-map paths", () => {
  const engine = readFileSync(join(publicDir, "face3d_engine.js"), "utf8");
  assert.match(engine, /from '\/face3d_geometry\.js'/);
  assert.match(engine, /from '\/face3d_support\.js'/);
});

test("service worker avoids stale undigested precache", () => {
  const sw = readFileSync(join(publicDir, "sw.js"), "utf8");
  assert.doesNotMatch(sw, /\/face\.js'/);
  assert.doesNotMatch(sw, /\/chat\.js'/);
  assert.match(sw, /OFFLINE_URL/);
});