import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
const viewsDir = join(root, "app", "views");

function partSources() {
  return [1, 2, 3, 4, 5].map((part) => readFileSync(join(publicDir, `face.part${part}.txt`), "utf8"));
}

test("face.js loads tail modules via MASTER_ASSET_PATHS after runtime", () => {
  const faceJs = readFileSync(join(publicDir, "face.js"), "utf8");
  const tail = readFileSync(join(publicDir, "face.part5.txt"), "utf8");
  assert.match(faceJs, /loadTailModules/);
  assert.match(faceJs, /MASTER_ASSET_PATHS\?\.faceModules/);
  assert.match(faceJs, /face_semantics\.js/);
  assert.doesNotMatch(tail, /await import\(/);
});

test("face.js warms stack on load and starts session on primer", () => {
  const faceJs = readFileSync(join(publicDir, "face.js"), "utf8");
  assert.match(faceJs, /master:face-stage/);
  assert.match(faceJs, /dispatchFaceStage\("modules"\)/);
  assert.match(faceJs, /dispatchFaceStage\("ready"\)/);
  assert.match(faceJs, /faceRuntime/);
  assert.match(faceJs, /faceModulesBundle/);
  assert.match(faceJs, /build_face_runtime/);
  assert.match(faceJs, /onPrimerSession/);
  assert.match(faceJs, /__MASTER_FACE_STACK_FAILED__/);
  assert.match(faceJs, /bootFaceStack\(\);/);
  assert.match(faceJs, /FACE3D_ACTIVE/);
  assert.doesNotMatch(faceJs, /addEventListener\("primer:ready", scheduleFaceStack/);
  assert.doesNotMatch(faceJs, /importFaceBlob/);
  assert.doesNotMatch(faceJs, /face\.part/);
});

test("face.modules.bundle.js is generated from face module entry", () => {
  const bundlePath = join(publicDir, "face.modules.bundle.js");
  assert.ok(existsSync(bundlePath), "run rails assets:build_face_modules_bundle");
  const bundle = readFileSync(bundlePath, "utf8");
  assert.match(bundle, /MASTER_FACE_PARTICLES|face_particles/);
  assert.match(bundle, /MASTER_FACE_BLEND|face_blendshape/);
});

test("face.runtime.js is generated from face parts", () => {
  const runtimePath = join(publicDir, "face.runtime.js");
  assert.ok(existsSync(runtimePath), "run rails assets:build_face_runtime");
  const runtime = readFileSync(runtimePath, "utf8");
  const part1 = readFileSync(join(publicDir, "face.part1.txt"), "utf8").trim();
  assert.match(runtime, /Generated by/);
  assert.ok(runtime.includes(part1.slice(0, 120)), "runtime should include part1 body");
});

test("shared boot partial uses 60s watchdog and error-live", () => {
  const boot = readFileSync(join(viewsDir, "shared", "_face_boot.html.erb"), "utf8");
  assert.match(boot, /60000/);
  assert.match(boot, /error-live/);
  assert.match(boot, /master:face-stage/);
  assert.match(boot, /master:session-ready/);
  assert.match(boot, /sessionReady/);
  assert.match(boot, /__MASTER_FACE_STACK_FAILED__/);
  assert.match(boot, /scheduleTextFallback/);
  assert.match(boot, /text-mode-session/);
  assert.match(boot, /dismissPrimer\(\)/);
  assert.match(boot, /form\.classList\.add\('gone'\)/);
  assert.match(boot, /ensurePrimer/);
  assert.doesNotMatch(boot, /showLoadState/);
  assert.match(boot, /pointerup/);
  assert.match(boot, /mousedown/);
  assert.match(boot, /click/);
  assert.match(boot, /touchend/);
  assert.match(boot, /primerTarget/);
  assert.match(boot, /syncPrimerRefs/);
  assert.match(boot, /syncShellRefs/);
  assert.match(boot, /watchFaceBoot/);
  assert.match(boot, /addEventListener\('click'/);
  assert.match(boot, /trackpadPrimary/);
  assert.match(boot, /primerTap/);
  assert.match(boot, /e\.button!==0/);
  assert.match(boot, /createElement\('button'\)/);
  assert.match(boot, /primerVisible/);
  assert.match(boot, /resetFaceSession/);
  assert.match(boot, /capture:false/);
  assert.match(boot, /__MASTER_PRIMER_TAP__/);
  assert.match(boot, /__MASTER_PRIMER_GO__/);
  assert.match(boot, /__MASTER_PRIMER_PENDING__/);
  assert.match(boot, /__MASTER_FACE_STATUS__/);
  assert.match(boot, /ev\.persisted/);
  assert.match(boot, /showFaceBehindPrimer/);
  assert.match(boot, /master:face-live/);
  assert.match(boot, /wirePrimerForm/);
  assert.match(boot, /primer-form/);
  assert.match(boot, /face-session/);
  assert.doesNotMatch(boot, /showBootError\('tap to retry'\)/);
  assert.match(boot, /armed=true/);
  assert.doesNotMatch(boot, /DOMContentLoaded/);
  assert.match(boot, /pinPrimer/);
  assert.doesNotMatch(boot, /15000/);
});

test("probe_chat_e2e script covers primer chat and felt state", () => {
  const probe = readFileSync(join(root, "script", "probe_chat_e2e.rb"), "utf8");
  const support = readFileSync(join(root, "script", "browser_probe_support.rb"), "utf8");
  const gemfile = readFileSync(join(root, "Gemfile"), "utf8");
  assert.match(probe, /probe_chat_e2e/);
  assert.match(probe, /browser_probe_support/);
  // ping/pong chat assertions live in the shared support module after the refactor.
  assert.match(support, /sendMessage\('ping'\)/);
  assert.match(support, /hasPong/);
  assert.match(probe, /MASTERFeltState/);
  assert.match(probe, /MASTER_FACE\?\.State/);
  assert.match(gemfile, /gem "ferrum"/);
  assert.match(probe, /MAX_PROBE_SECONDS/);
  assert.match(probe, /browser\.go_to\(URL\)/);
});

test("chat index ships import map and digested master_events", () => {
  const index = readFileSync(join(viewsDir, "chat", "index.html.erb"), "utf8");
  const helper = readFileSync(join(root, "app", "helpers", "face_assets_helper.rb"), "utf8");
  assert.match(index, /type="importmap"/);
  assert.match(index, /master_face_import_map/);
  assert.match(index, /asset_path\("master_events\.js"\)/);
  assert.match(index, /modulepreload/);
  assert.match(helper, /face3d_geometry\.js/);
  const bootIdx = index.indexOf('render "shared/face_boot"');
  const primerIdx = index.indexOf('id="primer"');
  const zshIdx = index.indexOf('id="zsh"');
  const face3dIdx = index.indexOf("face3d_preview.js");
  assert.ok(primerIdx > 0 && bootIdx > primerIdx, "primer must precede face_boot");
  assert.ok(zshIdx > 0 && bootIdx > zshIdx, "face_boot must run after #zsh exists in DOM");
  assert.ok(face3dIdx > 0 && face3dIdx < bootIdx, "face3d_preview.js may load before face_boot");
  assert.match(index, /__MASTER_PRIMER_TAP__/);
  assert.doesNotMatch(index, /onclick="window\.__MASTER_PRIMER_TAP__/);
  assert.match(index, /getElementById\('primer-form'\)/);
  assert.match(index, /addEventListener\('click',tap/);
  assert.match(index, /Critical primer layout/);
  assert.match(index, /id="primer-form"/);
  assert.match(index, /<button[^>]*type="button"[^>]*id="primer"/);
  assert.match(index, /face-live-badge/);
  assert.match(index, /id="primer-tier"/);
  assert.match(index, /tap to enter/);
  assert.match(index, /id="boot-wayfinding"/);
  assert.match(index, /data-step="audio"/);
  assert.match(index, /face_wayfinding\.js/);
  assert.match(index, /id="civic-status"/);
});

test("face_wayfinding.js tracks boot steps via master events", () => {
  const wayfinding = readFileSync(join(publicDir, "face_wayfinding.js"), "utf8");
  assert.match(wayfinding, /primer:ready/);
  assert.match(wayfinding, /master:face-ready/);
  assert.match(wayfinding, /master:container-ready/);
  assert.match(wayfinding, /master:session-ready/);
  assert.match(wayfinding, /boot-wayfinding/);
  assert.match(wayfinding, /civic-status/);
});

test("face3d preview announces live badge and boot brightness", () => {
  const preview = readFileSync(join(publicDir, "face3d_preview.js"), "utf8");
  const renderer = readFileSync(join(publicDir, "face3d_renderer.js"), "utf8");
  assert.match(preview, /announceFaceLive/);
  assert.match(preview, /master:face-live/);
  assert.match(preview, /bootBoost/);
  assert.match(preview, /1800/);
  assert.doesNotMatch(preview, /classList\.remove\("face-loading"\)/);
  assert.match(preview, /primerBlocking/);
  assert.match(preview, /primerBlocking\(\) && now - last < 80/);
  assert.match(renderer, /bootBoost/);
});

test("face.css keeps primer tappable until session and shows face behind overlay", () => {
  const css = readFileSync(join(publicDir, "face.css"), "utf8");
  assert.match(css, /body:not\(\.face-session\)/);
  assert.match(css, /face-behind-primer/);
  assert.match(css, /primer-form/);
  assert.match(css, /\.primer-form\.gone/);
  assert.match(css, /face-primed/);
  assert.match(css, /face-behind-primer="1"\] canvas#face/);
  assert.match(css, /body:not\(\.face-session\) \.top-left-logo/);
  assert.match(css, /calc\(var\(--z-primer\) \+ 3\)/);
});

test("face3d_engine imports use import-map paths", () => {
  const engine = readFileSync(join(publicDir, "face3d_engine.js"), "utf8");
  assert.match(engine, /from '\/face3d_geometry\.js'/);
  assert.match(engine, /from '\/face3d_support\.js'/);
  assert.match(engine, /applyBlendshape/);
});

test("visual_bridge defers SSE until session ready", () => {
  const bridge = readFileSync(join(publicDir, "visual_bridge.js"), "utf8");
  assert.match(bridge, /master:session-ready/);
  assert.match(bridge, /primer:ready/);
  assert.doesNotMatch(bridge, /observeDomSignals\(\);\n  connectSse\(\);/);
});

test("ecology render defers RAF until primer unlocks", () => {
  const ecology = readFileSync(join(publicDir, "cognition_ecology_render.js"), "utf8");
  assert.match(ecology, /primer:ready/);
  assert.doesNotMatch(ecology, /\n  ensureEcologyFrame\(\);\n  window\.addEventListener\("master:visual"/);
});

test("topology registry defers remote fetch until primer", () => {
  const registry = readFileSync(join(publicDir, "topology_registry.js"), "utf8");
  assert.match(registry, /primer:ready/);
  assert.doesNotMatch(registry, /\n  bootRemoteTopologies\(\);\n\}\)\(\);/);
});

test("chat_actions posts chat stream instead of EventSource GET", () => {
  const actions = readFileSync(join(publicDir, "chat_actions.js"), "utf8");
  assert.match(actions, /method:\s*"POST"/);
  assert.match(actions, /\/chat\/message/);
  assert.doesNotMatch(actions, /new EventSource\(/);
  assert.match(actions, /window\.MASTERChat/);
  assert.match(actions, /MASTER_FACE\?\.sendMessage/);
});

test("face runtime uses MASTERChat stream and digested particle worker", () => {
  const runtime = readFileSync(join(publicDir, "face.runtime.js"), "utf8");
  assert.match(runtime, /MASTERChat\.startChatStream/);
  assert.doesNotMatch(runtime, /new EventSource\(\s*`\/chat\/message/);
  assert.match(runtime, /MASTER_ASSET_PATHS\?\.particleWorker/);
  assert.doesNotMatch(runtime, /window\.sendMessage\s*=\s*sendMessage/);
  assert.match(runtime, /resetPrimer/);
});

test("service worker avoids stale undigested precache", () => {
  const sw = readFileSync(join(publicDir, "sw.js"), "utf8");
  assert.doesNotMatch(sw, /\/face\.js'/);
  assert.doesNotMatch(sw, /\/chat\.js'/);
  assert.match(sw, /OFFLINE_URL/);
  assert.match(sw, /Never cache digested/);
  assert.match(sw, /pathname\.startsWith\('\/assets\/'\)/);
});

test("face_deferred_loader schedules vision after primer", () => {
  const loader = readFileSync(join(publicDir, "face_deferred_loader.js"), "utf8");
  assert.match(loader, /face_vision\.bundle\.js/);
  assert.match(loader, /primer:ready/);
  assert.match(loader, /cognition_ecology/);
});

test("visual_governor reads runtime visual limits", () => {
  const governor = readFileSync(join(publicDir, "visual_governor.js"), "utf8");
  assert.match(governor, /MASTER_RUNTIME\?\.visual_limits/);
});