server:
  ip-address: 46.23.89.226
  hide-version: yes
  verbosity: 1
  username: _nsd
  zonesdir: "/var/nsd/zones/master"
  zonelistfile: "/var/nsd/db/zone.list"
  xfrdfile: "/var/nsd/run/xfrd.state"
  server-count: 2
  rrl-size: 1000000
  rrl-ratelimit: 200
  rrl-slip: 2
  rrl-whitelist-ratelimit: 2000

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1

zone:
  name: "bsdports.net"
  zonefile: "bsdports.net.zone"

  provide-xfr: 194.63.248.53 NOKEY
  provide-xfr: 151.249.124.1 NOKEY
  provide-xfr: 192.174.68.10 NOKEY
  provide-xfr: 151.249.126.3 NOKEY
  notify: 194.63.248.53 NOKEY
  notify: 151.249.124.1 NOKEY
  notify: 192.174.68.10 NOKEY
  notify: 151.249.126.3 NOKEY
