#!/bin/ksh
[ -r /etc/baibl.env ] && . /etc/baibl.env
[ -f /etc/rails/baibl.env ] && . /etc/rails/baibl.env
daemon="/usr/local/bin/bundle"
daemon_flags="exec env RAILS_ENV=production SECRET_KEY_BASE=${SECRET_KEY_BASE} HOME=/home/baibl falcon serve --bind http://127.0.0.1:10007"
daemon_user="baibl"
daemon_execdir="/home/baibl/app"
daemon_timeout="60"
. /etc/rc.d/rc.subr
pexp="ruby.*10007"
rc_bg=YES
rc_reload=NO
rc_cmd $1
