#!/bin/ksh
daemon="/usr/local/bin/litestream"
daemon_flags="replicate -config /etc/litestream.yml"
daemon_user="root"
daemon_execdir="/var/backups/litestream"
daemon_timeout="60"
. /etc/rc.d/rc.subr
pexp="litestream.*replicate.*-config /etc/litestream.yml"
rc_bg=YES
rc_reload=NO
rc_cmd $1
