# PubAttorney — legal services platform
source "https://rubygems.org"
ruby "~> 3.4"

gem "rails", "~> 8.1.2"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

gem "bcrypt", "~> 3.1.7"
gem "pundit"
gem "rotp"
gem "rqrcode"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "omniauth-github"
gem "omniauth-rails_csrf_protection"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "minitest", "~> 5.25"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end
gem "pagy"
gem "falcon"
gem "pub4-shared", path: "../shared"

gem "dartsass-rails", "~> 0.5.1"

gem "stimulus_reflex", "~> 3.5"
gem "futurism", "~> 1.4"