# frozen_string_literal: true

require "net/http"
require "uri"

module Ports
  module Openbsd
    # Fetches the package index over HTTPS.
    #
    # Replaces FtpIndexFetcher's target, which could not have worked: it asked
    # for ftp://ftp.openbsd.org/pub/OpenBSD/ports/<category>/INDEX, and measured
    # on 2026-08-05 that path is a 404 on the mirror (no ports/ directory exists
    # at the top level at all) while plain FTP to the host times out. The
    # per-category pipe-delimited INDEX that IndexParser expects is generated by
    # `make index` inside a ports tree; it is not published anywhere.
    class PackageIndexFetcher
      DEFAULT_BASE = "https://cdn.openbsd.org/pub/OpenBSD"
      DEFAULT_ARCH = "amd64"
      OPEN_TIMEOUT = 15
      READ_TIMEOUT = 60

      def initialize(platform:, base: nil, arch: nil, release: nil)
        @platform = platform
        @base = (base || ENV["BSDPORTS_MIRROR"] || https_base_for(platform)).chomp("/")
        @arch = arch || ENV.fetch("BSDPORTS_ARCH", DEFAULT_ARCH)
        @release = release || ENV["BSDPORTS_RELEASE"]
      end

      attr_reader :platform, :base, :arch

      # Newest numeric release directory on the mirror. Pinned by
      # BSDPORTS_RELEASE when an operator wants a specific one.
      def release
        @release ||= begin
          listing = get("#{base}/")
          releases = listing.to_s.scan(%r{href="(\d+\.\d+)/"}).flatten
          raise "no release directories at #{base}/" if releases.empty?

          releases.max_by { |r| r.split(".").map(&:to_i) }
        end
      end

      def index_url = "#{base}/#{release}/packages/#{arch}/index.txt"

      # Yields an IO of the index. Returns nil and logs when the mirror cannot
      # be reached — the caller decides whether that is fatal.
      def each_entry
        body = get(index_url)
        return nil if body.nil?

        Ports::Openbsd::PackageIndexParser.parse(StringIO.new(body))
      rescue StandardError => e
        Rails.logger.warn("bsdports package index fetch failed url=#{index_url} error=#{e.class}: #{e.message}")
        nil
      end

      private

      # Platform.mirror_url is an ftp:// URL kept for provenance; the same host
      # path serves over HTTPS, which is what OpenBSD mirrors actually offer.
      def https_base_for(platform)
        url = platform.mirror_url.to_s
        return DEFAULT_BASE if url.blank?

        url.sub(%r{\Aftp://}, "https://")
      end

      # A mirror is remote input, and `Location` is the mirror telling us where to
      # send our next request. URI.join followed it anywhere: a mirror that is
      # hostile, hijacked, or merely misconfigured could answer
      # `Location: http://169.254.169.254/latest/meta-data/` and this process would
      # fetch it from inside the box and hand the body to the parser. `base` is
      # operator input too — BSDPORTS_MIRROR, or a Platform row.
      #
      # So a redirect may move the path and may not move the host or drop TLS. That
      # is all an index mirror needs: cdn.openbsd.org redirects between paths, not
      # to other hosts. Anything else is refused loudly rather than followed,
      # because a silent nil here reads as an empty index, and an empty index reads
      # as "this platform has no packages".
      #
      # brgen's OutboundHttp is the fuller rule — it resolves the name and rejects
      # RFC1918, loopback and link-local — and it lives in another app. This is the
      # same principle at the one seam that needs it here, rather than a second copy
      # of that module. Folding OutboundHttp into RAILS/shared/ so both apps read
      # one rule is the larger move.
      def get(url, limit: 3)
        raise "too many redirects for #{url}" if limit.zero?

        uri = URI.parse(url)
        response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https",
                                                       open_timeout: OPEN_TIMEOUT, read_timeout: READ_TIMEOUT) do |http|
          http.get(uri.request_uri)
        end

        case response
        when Net::HTTPSuccess then response.body
        when Net::HTTPRedirection then follow(url, response["location"], limit)
        else
          Rails.logger.warn("bsdports mirror #{url} returned #{response.code}")
          nil
        end
      end

      def follow(from, location, limit)
        origin = URI.parse(from)
        target = URI.join(from, location.to_s)
        return get(target.to_s, limit: limit - 1) if same_origin?(origin, target)

        Rails.logger.error(
          "bsdports mirror #{origin.host} redirected off-host to " \
          "#{target.scheme}://#{target.host} — refused"
        )
        nil
      rescue URI::InvalidURIError, ArgumentError => e
        Rails.logger.error("bsdports mirror sent an unusable Location: #{e.class}: #{e.message}")
        nil
      end

      def same_origin?(origin, target)
        target.host.to_s.casecmp?(origin.host.to_s) && target.scheme == origin.scheme
      end
    end
  end
end
